### ISSUE TITLE
最新版本打开视频没有弹幕

### ISSUE THREAD

**Issue by GuiHva** [xjbeta/iina-plus#100]
IINA-1.2.0-Danmaku
IINA+ 0.5.14
B站链接
[https://www.bilibili.com/video/BV1iZ4y1w7q5]
![image](https://user-images.githubusercontent.com/37131861/112564485-50be3700-8e16-11eb-90e4-a3036ef2b5cf.png)
![image](https://user-images.githubusercontent.com/37131861/112564520-64699d80-8e16-11eb-976e-b8d3965a2932.png)

**Comment by xjbeta** [comment]
无法重现

**Comment by GuiHva** [comment]
我双击点了开了两个，一个没有弹幕，目前单击正常，有个小问题，有时候重新播放之前的视频链接会在结尾加一串数字
https://www.bilibili.com/video/BV1pf4y1t7Q9 <new added>?t=2460</>
导致无法播放，把?后面部分去掉就可以了

**Comment by xjbeta** [comment]
后面那部分t=XXX 应该是历史播放的时间  确实会导致无法解析
马上修复

开启多个iina+ 会导致无法连接到控制弹幕的本地websocket 服务器完成初始化
我试试能不能弹一个提示
