### ISSUE TITLE
经常性打开b站视频没有反应，有时候直播开播后，点开依然获取不到数据

### ISSUE THREAD

**Issue by SereinQH** [xjbeta/iina-plus#102]
问题：经常性打开b站视频没有反应，有时候直播开播后，点开依然获取不到数据，主要出现在斗鱼直播，需要重新打开软件才能获取到数据
建议：在收藏列表中，增加个刷新按钮，以便更新当前收藏的直播间的直播状态

**Comment by FQHlennon** [comment]
还有新版的软件的检查更新似乎有问题

**Comment by xjbeta** [comment]
Command + R 刷新
检查更新的内容都在GitHub 上   请使用“互联网”
