### ISSUE TITLE
能否支持一下cc直播

### ISSUE THREAD

**Issue by m174460635** [xjbeta/iina-plus#104]
如题,能否支持一下cc直播.

**Comment by coda1997** [comment]
同求，想看小秦

**Comment by xjbeta** [comment]
cc直播已支持
弹幕太复杂了  还没找到头绪

**Comment by coda1997** [comment]
可以提一个pl吗，一起来看看可否实现

发自Dadachen的iPhone

On Jul 7, 2021, at 11:06 AM, xjbeta ***@***.***> wrote:

﻿

cc直播已支持
弹幕太复杂了 还没找到头绪

**Comment by m174460635** [comment]
> 可以提一个pl吗，一起来看看可否实现 发自Dadachen的iPhone On Jul 7, 2021, at 11:06 AM, xjbeta ***@***.***> wrote: ﻿ cc直播已支持 弹幕太复杂了 还没找到头绪 — You are receiving this because you commented. Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fxjbeta%2Fiina-plus%2Fissues%2F104%23issuecomment-875235662&data=04%7C01%7C%7C3b3cd8e399ab467255b108d940f43421%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637612239859549898%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bBK0bCAVRGwQ%2BbDRXVXjYi%2BCF8BDBn8Gn0dWJgBkvrY%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEOENYN7IRF42XVNNLU7PDTTWPAC5ANCNFSM442WI4SA&data=04%7C01%7C%7C3b3cd8e399ab467255b108d940f43421%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637612239859559854%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PiQvyzVQ%2FAtMo%2BB093IGjbGOqobhtTc%2BE%2FPXd6%2BpmW4%3D&reserved=0>.

能看直播就很好了,我不看弹幕的.谢谢大佬

**Comment by TaoziDB** [comment]
> cc直播已支持
> 弹幕太复杂了 还没找到头绪

https://github.com/wbt5/real-url/blob/master/danmu/danmaku/cc.py
