### ISSUE TITLE
为什么不把 iina-danmaku 合并到 iina 呢？

### ISSUE THREAD

**Issue by CourierKyn** [xjbeta/iina-plus#11]

**Comment by xjbeta** [comment]
您好,
	iina-danmaku 弹幕的实现是用的 CommentCoreLibrary, 简单来说就是在iina 的视频画面上打开一个透明的网页, 在网页内显示弹幕内容.
归功于web 端弹幕的成熟, 实现非常简单, 各种方面效果也不错. 
	但是对于macOS swift 原生开发来说, 并不是一个很好的解决方案.
