### ISSUE TITLE
无法显示弹幕 显示404 

### ISSUE THREAD

**Issue by MG191** [xjbeta/iina-plus#110]
![1](https://user-images.githubusercontent.com/1240830/124698875-5995cd00-df1c-11eb-9008-70f5e392be30.jpg)

**Comment by xjbeta** [comment]
直播间号?  IINA+ 不会显示404 Not Found

**Comment by MG191** [comment]
> 直播间号? IINA+ 不会显示404 Not Found

不分哪个网站哪个直播间。所有直播间都是这样显示404。

**Comment by xjbeta** [comment]
在浏览器里打开 `http://127.0.0.1:19080/danmaku/index.htm`
显示`404 Not Found`吗

**Comment by MG191** [comment]
是的，浏览器打开显示404 Not Found。

**Comment by xjbeta** [comment]
不清楚你的网络是什么情况   本地的网页服务器都404

**Comment by MG191** [comment]
和罗技 Logi Options+ 软件端口冲突，卸载就正常了。请问能自定义端口吗？

**Comment by xjbeta** [comment]
IINA 弹幕版里是写死的
我两边一起更新一下

**Comment by MG191** [comment]
> IINA 弹幕版里是写死的
> 我两边一起更新一下

Logi Options+ 这个软件还处于测试。不知道罗技最后的正式版是什么情况，是否还会有端口冲突的情况。使用正式版的Logi Options 并不会出现端口冲突的情况。
