### ISSUE TITLE
直播没有弹幕

### ISSUE THREAD

**Issue by ggfggggjqd** [xjbeta/iina-plus#112]
HttpServer.swift[129], start(): Server has started ( port = 19080 ). Try to connect now...
AppDelegate.swift[36], applicationDidFinishLaunching(_:): App did finish launch
AppDelegate.swift[39], applicationDidFinishLaunching(_:): App Version 0.5.19 (Build 21080617)
AppDelegate.swift[40], applicationDidFinishLaunching(_:): macOS Version 11.5.1 (Build 20G80)
AppDelegate.swift[67], initImageCache(): Disk cache size: 0.9411096572875977 MB
MainViewController.swift[383], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
MainViewController.swift[415], startSearchingUrl(_:directly:): decodeUrl success: https://www.douyu.com/6657
MainViewController.swift[415], startSearchingUrl(_:directly:): decodeUrl success: https://www.douyu.com/6657
VideoGet.swift[1082], saveDMFile(_:with:): Saved DM in /Users/dominator/Library/Application Support/com.xjbeta.iina-plus/danmaku/danmaku-4D1C66D0-A6E5-418C-BA01-69544A316106.xml
Processes.swift[333], openWithIINAUrlScheme(_:args:uuid:): Open IINA args:  url=https://pcdn-a1a.douyucdn.cn/live/6979222rp6Gz3Ohl.flv?wsAuth=54fa772ff086baee3df3c2d9d85275cd&token=web-h5-0-6979222-28771e3d51a2a69bfa016230acdabc36511879764559f0af&logo=0&expire=0&did=99bf2d3d3debf7958e2aa1f100011601&ver=Douyu_219111405&pt=2&st=0&origin=tct&mix=0&isp=👻mpv_force-media-title=BNB VS VITALITY BO3👻mpv_ytdl=no👻danmaku👻uuid=4D1C66D0-A6E5-418C-BA01-69544A316106👻directly
Processes.swift[346], openWithIINAUrlScheme(_:args:uuid:): Open IINA URL:  iina://iina-plus.base64?dXJsPWh0dHBzOi8vcGNkbi1hMWEuZG91eXVjZG4uY24vbGl2ZS82OTc5MjIycnA2R3ozT2hsLmZsdj93c0F1dGg9NTRmYTc3MmZmMDg2YmFlZTNkZjNjMmQ5ZDg1Mjc1Y2QmdG9rZW49d2ViLWg1LTAtNjk3OTIyMi0yODc3MWUzZDUxYTJhNjliZmEwMTYyMzBhY2RhYmMzNjUxMTg3OTc2NDU1OWYwYWYmbG9nbz0wJmV4cGlyZT0wJmRpZD05OWJmMmQzZDNkZWJmNzk1OGUyYWExZjEwMDAxMTYwMSZ2ZXI9RG91eXVfMjE5MTExNDA1JnB0PTImc3Q9MCZvcmlnaW49dGN0Jm1peD0wJmlzcD3wn5G7bXB2X2ZvcmNlLW1lZGlhLXRpdGxlPUJOQiBWUyBWSVRBTElUWSBCTzPwn5G7bXB2X3l0ZGw9bm/wn5G7ZGFubWFrdfCfkbt1dWlkPTREMUM2NkQwLUE2RTUtNDE4Qy1CQTAxLTY5NTQ0QTMxNjEwNvCfkbtkaXJlY3RseQ==

**Comment by xjbeta** [comment]
测试没有任何问题
斗鱼的其他直播、其他平台的直播、B站主站的视频有弹幕吗

**Comment by ggfggggjqd** [comment]
重启之后就好了哈哈哈哈

**Comment by NSFish** [comment]
> 测试没有任何问题
> 斗鱼的其他直播、其他平台的直播、B站主站的视频有弹幕吗

我这也没弹幕，看了一下，main.js 的默认端口号是 10980，而 Swift 这边的默认端口号是 19080，我把 main.js 的改成 19080 就 OK 了。。

**Comment by xjbeta** [comment]
> > 测试没有任何问题
> > 斗鱼的其他直播、其他平台的直播、B站主站的视频有弹幕吗
> 
> 我这也没弹幕，看了一下，main.js 的默认端口号是 10980，而 Swift 这边的默认端口号是 19080，我把 main.js 的改成 19080 就 OK 了。。

手快打错了(    马上修复
