### ISSUE TITLE
主窗口只有收藏

### ISSUE THREAD

**Issue by Kito0615** [xjbeta/iina-plus#116]
下载最新版 dmg安装后，只显示收藏
![](https://i.loli.net/2021/08/27/HmoVMuK3Ub6OjPk.png)
App Version 0.5.20 (Build 21081917)
macOS 版本 10.12.6（版号 16G2136）
iMac12,2, Intel Core i5

**Comment by Kito0615** [comment]
我重装了0.5.18版本，发现是因为滚动引起的。然后又使用0.5.20版本，原因是一样的。0.5.20版本截图
![](https://i.loli.net/2021/08/31/umicYqW9Mz8rTOA.png)。感觉是左侧布局出错了。不知道你是使用的AutoLayout还是ResizingMask？

**Comment by xjbeta** [comment]
ScrollView 的约束问题  试试修好了没
[IINA+.app.zip](https://github.com/xjbeta/iina-plus/files/7080806/IINA%2B.app.zip)

**Comment by Kito0615** [comment]
现在好了。
