### ISSUE TITLE
斗鱼直播间打不开

### ISSUE THREAD

**Issue by NSFish** [xjbeta/iina-plus#124]
```swift
private func douyuEvaluateJavaScript(_ javaScriptString: String) -> Promise<(String)> {
        return Promise { resolver in
            douyuWebview.evaluateJavaScript(javaScriptString) { (re, error) in
                // 传回来的 re 是 nil
                guard let str = re as? String, error == nil else {
                    resolver.reject(error!)
                    return
                }
                resolver.fulfill(str)
            }
        }
    }
```

**Comment by xjbeta** [comment]
无法重现  依旧有问题请补充直播间链接

**Comment by NSFish** [comment]
> 无法重现 依旧有问题请补充直播间链接

随便一个斗鱼直播间链接都会打不开，比如 https://www.douyu.com/55353。
传入的 javaScriptString 打印出来是 "window.ub98484234(55353, \'9fe36497d24b402bd14d5a50ac69138b\', 1639320362);"

**Comment by xjbeta** [comment]
还是无法重现

试试用Safari 设置 - 高级 - 勾选  显示“开发”菜单
打开这个直播间  然后空白处右键 - 检查元素 - 控制台 - 输入`window.ub98484234(55353, '9fe36497d24b402bd14d5a50ac69138b', 1639320362);`  按回车
看看会打印什么

**Comment by NSFish** [comment]
> 还是无法重现
> 
> 试试用Safari 设置 - 高级 - 勾选 显示“开发”菜单 打开这个直播间 然后空白处右键 - 检查元素 - 控制台 - 输入`window.ub98484234(55353, '9fe36497d24b402bd14d5a50ac69138b', 1639320362);` 按回车 看看会打印什么

"v=220120211212&did=9fe36497d24b402bd14d5a50ac69138b&tt=1639320362&sign=00dbd33041b7e07e8ceb9f64f020dd21" = $1

**Comment by xjbeta** [comment]
可能暂时无法解决  我尝试把这部分加密算法  放进javascriptcore 里看看

**Comment by NSFish** [comment]
> 可能暂时无法解决 我尝试把这部分加密算法 放进javascriptcore 里看看

Hi，经尝试，我发现把代理软件[ClashX](https://github.com/yichengchen/clashX)关掉后，douyuEvaluateJavaScript 就能正常工作了😂。
于是有了一个治标的方法：
在 ClashX 的配置文件里加入
```yaml
- DOMAIN-SUFFIX,ytimg.com,Proxy
```
其他代理软件依样画葫芦即可。

至于为什么只有斗鱼会这样，我就不知道了，因为 huya.com 同样不在我的配置文件里😂。

**Comment by AlaiaS** [comment]
我在代理配置文件里加入了，但是依然是只能打开弹幕，但是没有视频图像和音频

**Comment by AlaiaS** [comment]
我代理配置中加入了，但依然没有办法打开直播间，只有弹幕，没有视频
