### ISSUE TITLE
希望支持b站的合集和列表

### ISSUE THREAD

**Issue by Fre-ak** [xjbeta/iina-plus#125]
可以看b站的直播回放
另外, 希望能增加一个默认清晰度的功能, 现在要多点一下选择清晰度

**Comment by lowking** [comment]
希望能增加一个默认清晰度的功能, 现在要多点一下选择清晰度+1

**Comment by zhangnew** [comment]
已经有了自动打开解析结果的功能 https://github.com/xjbeta/iina-plus/commit/a360121b07c1a586f3390a6da6f38596ed8a4d8c

期待支持合集列表功能！

**Comment by kooonnn** [comment]
没有 cover 到新版式直播间，导致解析异常
![iina+](https://user-images.githubusercontent.com/20886636/195079800-3c399a7f-7c0e-4ca5-a6b3-79e4e999a641.png)
例如：https://live.bilibili.com/12235923 会解析到 https://api.live.bilibili.com/xlive/web-room/v1/index/getRoomBaseInfo?room_ids=23945568&room_ids=12235923&room_ids=14327465&room_ids=21396545&room_ids=24808180&room_ids=24812685&room_ids=24812759&req_biz=web_room_componet
可选添加解析旧版直播间：https://live.bilibili.com/blanc/12235923
