### ISSUE TITLE
日后能增加更多的功能让他变成B站mac客户端吗

### ISSUE THREAD

**Issue by lixiao189** [xjbeta/iina-plus#135]
能看弹幕了感觉非常不错，下次能增加搜索视频功能和获取首页推荐功能吗，然后再加一个弹幕发送功能！感谢作者的奉献

**Comment by xjbeta** [comment]
近期开发重点是直播  B站只是顺带写了(而且内置一个播放器播放主站的话  会有不少问题)
你说的几个功能  都不在我自己的使用需求内(

**Comment by lixiao189** [comment]
okk，懂了
