### ISSUE TITLE
弹幕字体失效

### ISSUE THREAD

**Issue by zhhanging** [xjbeta/iina-plus#140]
弹幕字体显示为宋体，在设置中更换不同字体之后不生效。
<img width="1327" alt="CleanShot 2022-04-01 at 23 11 29@2x" src="https://user-images.githubusercontent.com/39266588/161291610-01449bee-193b-4a81-9c62-5cd24536fea5.png">

AppDelegate.swift[36], applicationDidFinishLaunching(_:): App did finish launch
AppDelegate.swift[39], applicationDidFinishLaunching(_:): App Version 0.6.5 (Build 22032423)
AppDelegate.swift[40], applicationDidFinishLaunching(_:): macOS 版本12.3.1（版号21E258）
AppDelegate.swift[43], applicationDidFinishLaunching(_:): CoreData Path: /Users/hang/Library/Application Support/IINA+/DataModel.sqlite
AppDelegate.swift[67], initImageCache(): Image Cache Path: /Users/hang/Library/Caches/com.hackemist.SDImageCache/default
HttpServer.swift[280], prepareWebSiteFiles(): /Applications/iina+.app/Contents/Resources/WebFiles
HttpServer.swift[281], prepareWebSiteFiles(): /Users/hang/Library/Application Support/com.xjbeta.iina-plus/WebFiles
HttpServer.swift[249], start(): Server has started ( port = 19080 ). Try to connect now...
MainViewController.swift[499], startSearchingUrl(_:directly:): decodeUrl success: https://www.bilibili.com/video/BV1YY4y1v7Hm
VideoGet.swift[1092], saveDMFile(_:with:): Saved DM in /Users/hang/Library/Application Support/com.xjbeta.iina-plus/WebFiles/danmaku-CD8EDF46-0899-4284-8B82-19571B4FD486.xml
HttpServer.swift[64], register(_:site:url:): Prepare DM block list error: Error Domain=NSCocoaErrorDomain Code=4 "文件“Block-List-Plus.xml”不存在。" UserInfo={NSSourceFilePathErrorKey=/Applications/iina+.app/Contents/Resources/Block-List-Plus.xml, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/Applications/iina+.app/Contents/Resources/Danmaku/iina-plus-blockList.xml, NSFilePath=/Applications/iina+.app/Contents/Resources/Block-List-Plus.xml, NSUnderlyingError=0x600002a84390 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Processes.swift[246], openWithURLScheme(_:): openWithURLScheme iina://iina-plus.base64?dXJsPWh0dHBzOi8vdXBvcy1zei1taXJyb3Jjb3NvMS5iaWxpdmlkZW8uY29tL3VwZ2N4Y29kZS8wMS84NC81NjQ2MDg0MDEvNTY0NjA4NDAxX25iMi0xLTMwMTEyLm00cz9lPWlnOGV1eFpNMnJOY05iZGxob052TkM4QnFKSXpOYmZxWEJ2RXF4VEV0bzhCVHJOdk4wR3ZUOTBXNUpaTWtYX1lOME12WGc4Z05FVjROQzh4TkVWNE4wM2VOMEI1dFpscU54VEV0bzhCVHJOdk5lWlZ1SjEwS2pfZzJVQjAySjBtTjBCNXRabHFOQ05FdG84QlRyTnZOQzdNVFg1MDJDOGYyam1NUUo2bXFGMmZrYTFtcXg2Z3FqMGVOMEI1OTlNPSZ1aXBrPTUmbmJzPTEmZGVhZGxpbmU9MTY0ODgzMzA2NCZnZW49cGxheXVybHYyJm9zPWNvc28xYnYmb2k9MjA4NjI4Nzc4NyZ0cmlkPWY2ZTJjYTdjNmY3MzRkOWZhZWM5NWE4YjdmZjE4NDhmdSZwbGF0Zm9ybT1wYyZ1cHNpZz1kN2Q2YmJiMjdhZjI1ZGYxY2UzN2FlMTBkODA0NDE1MSZ1cGFyYW1zPWUsdWlwayxuYnMsZGVhZGxpbmUsZ2VuLG9zLG9pLHRyaWQscGxhdGZvcm0mbWlkPTI3NjE5ODQmYnZjPXZvZCZuZXR0eXBlPTAmb3JkZXJpZD0wLDMmYWdycj0xJmJ3PTE2NzAxNCZsb2dvPTgwMDAwMDAw8J+Ru21wdl9mb3JjZS1tZWRpYS10aXRsZT3jgJDnp5HmioDpk77jgJHnp5HmioDmlrDpl7vliqDplb/nr4fvvIHoi7nmnpxNMuWkhOeQhuWZqOaAp+iDvei2hei2ik0xIEFNROaYvuWNoeaAp+iDveWujOeIhkludGVsIFvnp5HmioDpk75UZWNoTGlua2VkICM2OTY5XfCfkbttcHZfeXRkbD1ub/CfkbttcHZfcmVmZXJyZXI9aHR0cHM6Ly93d3cuYmlsaWJpbGkuY29tL/CfkbttcHZfYXVkaW8tZmlsZT1odHRwczovL3Vwb3Mtc3otbWlycm9yY29zLmJpbGl2aWRlby5jb20vdXBnY3hjb2RlLzAxLzg0LzU2NDYwODQwMS81NjQ2MDg0MDFfbmIyLTEtMzAyMTYubTRzP2U9aWc4ZXV4Wk0yck5jTmJkbGhvTnZOQzhCcUpJek5iZnFYQnZFcXhURXRvOEJUck52TjBHdlQ5MFc1SlpNa1hfWU4wTXZYZzhnTkVWNE5DOHhORVY0TjAzZU4wQjV0WmxxTnhURXRvOEJUck52TmVaVnVKMTBLal9nMlVCMDJKMG1OMEI1dFpscU5DTkV0bzhCVHJOdk5DN01UWDUwMkM4ZjJqbU1RSjZtcUYyZmthMW1xeDZncWowZU4wQjU5OU09JnVpcGs9NSZuYnM9MSZkZWFkbGluZT0xNjQ4ODMzMDY0Jmdlbj1wbGF5dXJsdjImb3M9Y29zYnYmb2k9MjA4NjI4Nzc4NyZ0cmlkPWY2ZTJjYTdjNmY3MzRkOWZhZWM5NWE4YjdmZjE4NDhmdSZwbGF0Zm9ybT1wYyZ1cHNpZz00MjhhYjhjNmI0OGRlYTY4ODY5YjAxZjkxMGQ0MmI1ZSZ1cGFyYW1zPWUsdWlwayxuYnMsZGVhZGxpbmUsZ2VuLG9zLG9pLHRyaWQscGxhdGZvcm0mbWlkPTI3NjE5ODQmYnZjPXZvZCZuZXR0eXBlPTAmb3JkZXJpZD0wLDMmYWdycj0xJmJ3PTg0MTAmbG9nbz04MDAwMDAwMPCfkbtkYW5tYWt18J+Ru3V1aWQ9Q0Q4RURGNDYtMDg5OS00Mjg0LThCODItMTk1NzFCNEZENDg28J+Ru2RtUG9ydD0xOTA4MPCfkbtkaXJlY3RseQ==.
HttpServer.swift[196], start(): Websocket client connected.
HttpServer.swift[158], start(): Optional(["https://www.bilibili.com/video/BV1YY4y1v7Hm"])
HttpServer.swift[308], send(_:text:id:): WriteText to websocket: {"method":"dmBlockList","text":"底部, List"}
HttpServer.swift[308], send(_:text:id:): WriteText to websocket: {"method":"dmSpeed","text":"563"}
HttpServer.swift[308], send(_:text:id:): WriteText to websocket: {"method":"dmOpacity","text":"0.456592345505618"}
HttpServer.swift[308], send(_:text:id:): WriteText to websocket: {"method":"loadDM","text":""}

**Comment by jie17** [comment]
@xjbeta 
https://github.com/xjbeta/iina-plus/blob/acc99cb379134e1ca0165e8973b5e9479c7340bd/IINA%2B/Utils/Danmaku.swift#L203
这里的 `return` 是不是忘记删了，我试了一下删了以后就可以显示设置的字体了

**Comment by xjbeta** [comment]
这部分是准备删除后  全部转到弹幕插件的
但IINA 一直拖着没更新  某个版本不小心一起提交了....
