### ISSUE TITLE
斗鱼直播间打不开

### ISSUE THREAD

**Issue by zhea55** [xjbeta/iina-plus#141]
直播间链接：https://www.douyu.com/52876

看起来像是证书有问题。代码里面能不能忽略证书错误？

MainViewController.swift[517], startSearchingUrl(_:directly:): sessionTaskFailed(error: Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, NSErrorPeerCertificateChainKey=(
    "<cert(0x7f84fb83dc00) s: *.livehwc3.cn i: GlobalSign RSA OV SSL CA 2018>"
), NSErrorClientCertificateStateKey=0, NSErrorFailingURLKey=https://dyp2p-hw.douyucdn.cn/52876rxT9k6LtODz.xs, NSErrorFailingURLStringKey=https://dyp2p-hw.douyucdn.cn/52876rxT9k6LtODz.xs, NSUnderlyingError=0x6000024e4840 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x600001a53340>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, kCFStreamPropertySSLPeerCertificates=(
    "<cert(0x7f84fb83dc00) s: *.livehwc3.cn i: GlobalSign RSA OV SSL CA 2018>"
)}}, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <0D564440-73C1-4D3E-8B4F-2F1AC0374B59>.<34>"
), _kCFStreamErrorCodeKey=-9802, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <0D564440-73C1-4D3E-8B4F-2F1AC0374B59>.<34>, NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x600001a53340>, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made.})

**Comment by xjbeta** [comment]
无法重现  建议先检查网络环境

**Comment by zhea55** [comment]
> 无法重现 建议先检查网络环境

嗯 确实是的。我用了一个去广告的DNS，可能斗鱼的某些链接被屏蔽了。
