### ISSUE TITLE
无话可说

### ISSUE THREAD

**Issue by pig-tongzhi** [xjbeta/iina-plus#142]

**Comment by pig-tongzhi** [comment]
从知乎的连接点进来，下载完代码之后就不知道怎么办了，文档也阅读不明白，太难了，有中文文档就好了

**Comment by pig-tongzhi** [comment]
测试一下梯子搭好了没有

**Comment by xjbeta** [comment]
虽然不知道你想要什么  姑且认为你是想要在Xcode 里跑起来
那么你需要 release 版本的macOS 和Xcode
然后`git clone https://github.com/xjbeta/iina-plus`
打开`iina-plus` 文件夹  双击打开(Xcode)`IINA+.xcodeproj`
等待Xcode 自动下载完 Swift Package Manager 里的依赖就能 run 了  (请自行解决SPM的网络问题)

这些都是最基础的  基本没有项目会额外说明怎么操作

**Comment by pig-tongzhi** [comment]
感谢您的回复，我以为下载出来的就是直接双击然后就直接生成一个应用程序了呢，

这也是我的疑问所在，怎么能把文件变成应用程序，如果有冒犯的地方实在不好意思
![Uploading image.png…]()

**Comment by icodea** [comment]
[Releases](https://github.com/xjbeta/iina-plus/releases) 里直接下载0.6.6版本的安装包安装就好了呀，再搭配IINA使用
