### ISSUE TITLE
昨天更新了一个版本，任何直播流 都打不开了

### ISSUE THREAD

**Issue by Zostana** [xjbeta/iina-plus#144]

**Comment by Zostana** [comment]
你们有遇到这样的情况吗

**Comment by xjbeta** [comment]
最新的一个版本  整理了所有直播解析相关的代码
重启IINA+ 然后解析几个直播网站  把 `帮助 - 日志文件`  里的内容  发来看看

**Comment by Zostana** [comment]
> 最新的一个版本 整理了所有直播解析相关的代码 重启IINA+ 然后解析几个直播网站 把 `帮助 - 日志文件` 里的内容 发来看看

测试了  b站的打不开了，斗鱼 还可以

**Comment by Zostana** [comment]
AppDelegate.swift[36], applicationDidFinishLaunching(_:): App did finish launch
AppDelegate.swift[39], applicationDidFinishLaunching(_:): App Version 0.6.6 (Build 22042822)
AppDelegate.swift[40], applicationDidFinishLaunching(_:): macOS 版本12.3.1（版号21E258）
AppDelegate.swift[43], applicationDidFinishLaunching(_:): CoreData Path: /Users/zhangsainan/Library/Application Support/IINA+/DataModel.sqlite
AppDelegate.swift[67], initImageCache(): Image Cache Path: /Users/zhangsainan/Library/Caches/com.hackemist.SDImageCache/default
HttpServer.swift[280], prepareWebSiteFiles(): /Applications/IINA+.app/Contents/Resources/WebFiles
HttpServer.swift[281], prepareWebSiteFiles(): /Users/zhangsainan/Library/Application Support/com.xjbeta.iina-plus/WebFiles
HttpServer.swift[249], start(): Server has started ( port = 19080 ). Try to connect now...
MainViewController.swift[392], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
MainViewController.swift[454], startSearchingUrl(_:directly:): decodeUrl success: https://live.bilibili.com/7777
VideoGet.swift[79], prepareDanmakuFile(yougetJSON:id:): Ignore Danmaku download.
Processes.swift[246], openWithURLScheme(_:): openWithURLScheme iina://open?url=%2Fvar%2Ffolders%2Fp4%2Frdkzmkdn541fjw52schp2vzw0000gn%2FT%2FIINA-PLUS%2F499D7AA4-2A72-47DF-B599-43C068691415.m3u&mpv_force-media-title=%E5%BE%B7%E4%BA%91%E8%89%B2%20%E6%96%B0%E7%89%88%E6%9C%AC%E4%B8%8A%E5%88%86%E5%A6%82%E5%96%9D%E6%B1%A4%EF%BC%81&mpv_ytdl=no.
MainViewController.swift[454], startSearchingUrl(_:directly:): decodeUrl success: https://live.bilibili.com/7777
VideoGet.swift[79], prepareDanmakuFile(yougetJSON:id:): Ignore Danmaku download.
Processes.swift[246], openWithURLScheme(_:): openWithURLScheme iina://open?url=%2Fvar%2Ffolders%2Fp4%2Frdkzmkdn541fjw52schp2vzw0000gn%2FT%2FIINA-PLUS%2F931D5A8D-0A95-4508-ABAC-9985B385FF75.m3u&mpv_force-media-title=%E5%BE%B7%E4%BA%91%E8%89%B2%20%E6%96%B0%E7%89%88%E6%9C%AC%E4%B8%8A%E5%88%86%E5%A6%82%E5%96%9D%E6%B1%A4%EF%BC%81&mpv_ytdl=no.
MainViewController.swift[454], startSearchingUrl(_:directly:): decodeUrl success: https://www.douyu.com/5067522
VideoGet.swift[79], prepareDanmakuFile(yougetJSON:id:): Ignore Danmaku download.
Processes.swift[246], openWithURLScheme(_:): openWithURLScheme iina://open?url=%2Fvar%2Ffolders%2Fp4%2Frdkzmkdn541fjw52schp2vzw0000gn%2FT%2FIINA-PLUS%2F651B3F16-F7E6-439F-864D-564D9A80ED8D.m3u&mpv_force-media-title=%E8%A7%A3%E8%AF%B4%E7%B1%B3%E5%8B%92%EF%BC%9A%E4%B8%8B%E6%A3%8B~&mpv_ytdl=no.
MainViewController.swift[454], startSearchingUrl(_:directly:): decodeUrl success: https://live.bilibili.com/7777
VideoGet.swift[79], prepareDanmakuFile(yougetJSON:id:): Ignore Danmaku download.
Processes.swift[246], openWithURLScheme(_:): openWithURLScheme iina://open?url=%2Fvar%2Ffolders%2Fp4%2Frdkzmkdn541fjw52schp2vzw0000gn%2FT%2FIINA-PLUS%2F299642D8-6883-4E6E-91E1-FA4B7169CC3B.m3u&mpv_force-media-title=%E5%BE%B7%E4%BA%91%E8%89%B2%20%E6%96%B0%E7%89%88%E6%9C%AC%E4%B8%8A%E5%88%86%E5%A6%82%E5%96%9D%E6%B1%A4%EF%BC%81&mpv_ytdl=no.
MainViewController.swift[454], startSearchingUrl(_:directly:): decodeUrl success: https://live.bilibili.com/7777
VideoGet.swift[79], prepareDanmakuFile(yougetJSON:id:): Ignore Danmaku download.
Processes.swift[246], openWithURLScheme(_:): openWithURLScheme iina://open?url=%2Fvar%2Ffolders%2Fp4%2Frdkzmkdn541fjw52schp2vzw0000gn%2FT%2FIINA-PLUS%2F9C0470F4-3718-44DF-AA30-12CE4D9B9E6E.m3u&mpv_force-media-title=%E5%BE%B7%E4%BA%91%E8%89%B2%20%E6%96%B0%E7%89%88%E6%9C%AC%E4%B8%8A%E5%88%86%E5%A6%82%E5%96%9D%E6%B1%A4%EF%BC%81&mpv_ytdl=no.

**Comment by Zostana** [comment]
这是日志

**Comment by xjbeta** [comment]
B站最近有些抽搐  很容易打不开直播链接 (网络错误 475)  
重启下网络接口  换个ip 似乎能解决
上个更新就是退回旧版本API的  暂时还是不稳定
可以试试下面这个版本  能不能长时间使用  (IINA 打开链接会很慢)

[IINA+ 0.6.6.zip](https://github.com/xjbeta/iina-plus/files/8599068/IINA%2B.0.6.6.zip)

**Comment by xjbeta** [comment]
0.6.7 添加referer 后能稳定解析了
