### ISSUE TITLE
解析cc.163.com直播链接失败； can not open cc.163 

### ISSUE THREAD

**Issue by oldwinter** [xjbeta/iina-plus#145]
such as：https://cc.163.com/260510797/ ，already newest version：版本0.6.7 (22050322)
err screenshot：
<img width="500" alt="image" src="https://user-images.githubusercontent.com/8112159/168011413-274c55ec-24b8-4290-baa7-302face20e17.png">

MainViewController.swift[472], startSearchingUrl(_:directly:): Error Domain=NSCocoaErrorDomain Code=3840 "Unable to parse empty data." UserInfo={NSDebugDescription=Unable to parse empty data.}

**Comment by xjbeta** [comment]
0.6.8 已修复
