### ISSUE TITLE
希望可以增加rss的订阅功能

### ISSUE THREAD

**Issue by ayanamimcy** [xjbeta/iina-plus#148]
希望可以增加rss的订阅功能，这样就可以实现自定义的视频列表合集了

**Comment by xjbeta** [comment]
没明白你想要什么效果
直播/B站视频和rss订阅好像也没什么关系

**Comment by ayanamimcy** [comment]
rss可以订阅  视频合集 也可以订阅up主的视频发布，这样想重点关注谁的视频，直接订阅对应的rss就可以了。就不需要打开b站网页了。

<img width="948" alt="image" src="https://user-images.githubusercontent.com/8985285/169649977-8cb709d6-3ac6-4786-a0d2-78be37d9122a.png">

**Comment by xjbeta** [comment]
为什么不用账号关注了  然后登陆账号呢
