### ISSUE TITLE
B站的直播用内置的flv.js打不开

### ISSUE THREAD

**Issue by 0x1301FDF** [xjbeta/iina-plus#149]
B站的直播用内置的flv.js打不开，用iina可以打开
链接是 https://live.bilibili.com/555

JSPlayerViewController.swift[538], webView(_:didFinish:): Finish
JSPlayerViewController.swift[552], windowWillClose(_:): windowWillClose
没详细的相关日志了

**Comment by xjbeta** [comment]
B站直播添加了referrer 验证  由于WKWebKit 的安全机制  无法解决
