### ISSUE TITLE
感觉b站的弹幕屏蔽功能没有生效呢

### ISSUE THREAD

**Issue by ayanamimcy** [xjbeta/iina-plus#152]
这是我的配置
![image](https://user-images.githubusercontent.com/8985285/170624786-f4c40222-c474-4715-be80-29b7f6c02d7f.png)

这是弹幕的情况
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/8985285/170624766-6a08e167-9571-42c1-adf6-ed2a717a5d20.png">

**Comment by xjbeta** [comment]
IINA+ 中文时屏蔽失效  下版本修复  或者使用插件版
