### ISSUE TITLE
请问为何内置的flv.fs播放器B站的直播都打不开，不停的转圈。但是iina又能打开？

### ISSUE THREAD

**Issue by loveproe** [xjbeta/iina-plus#154]
还有B站直播选了hevc也还是avc解码，这个设置没起效呀。

**Comment by xjbeta** [comment]
B站加了referer 防盗链  解决不了
不是每个清晰度  都有hevc  只是优先选择hevc

**Comment by loveproe** [comment]
> B站加了referer 防盗链 解决不了 不是每个清晰度 都有hevc 只是优先选择hevc

谢谢你，这个问题没事，但是内置的flv播放器b站直播这个问题你那不能重现吗？还有，就是最新的0.6.12版本出现了，这个内置的播放器关闭了，声音还能持续2-3秒钟，很奇怪，上个版本都没出现。

**Comment by xjbeta** [comment]
下版本修复声音的问题
研究了一下  B站直播有办法解决  但是B站不能稳定提供hevc 的播放链接  估计体验会非常差

**Comment by loveproe** [comment]
> 下版本修复声音的问题 研究了一下 B站直播有办法解决 但是B站不能稳定提供hevc 的播放链接 估计体验会非常差

谢谢🙏回复。主要是内置的播放器播放4k直播不会卡顿，iina播放4k直播总是丢帧。一个贪心的要求内置的播放器能否支持一下全屏快捷键，现在软件上面显示的快捷键fnF不起作用呀，能否改成F或者command+f。现在太麻烦了，每次都要左上角点击最大化。
