### ISSUE TITLE
虎牙弹幕不太稳定

### ISSUE THREAD

**Issue by AjianYo** [xjbeta/iina-plus#159]
偶尔出现弹幕刷不出来的情况，刷新三四次才会出来，望修复🍗🍗🍗

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by xjbeta** [comment]
`Danmaku.swift[179], loadDM(): Init huya AnchorUid failed Error Domain=NSCocoaErrorDomain Code=3840 "Unable to parse empty data." UserInfo={NSDebugDescription=Unable to parse empty data.}.`
刚好遇到了  似乎是有时候会找不到某个UID
