### ISSUE TITLE
请问为什么一直something went wrong呀

### ISSUE THREAD

**Issue by lethefrost** [xjbeta/iina-plus#16]
ಠ_ಠ

**Comment by xjbeta** [comment]
- 接口失效了
- 高频请求  被服务器暂时屏蔽了
- 不支持
- 检查更新  最新版本  Version 0.4.5 (19022812)
- 网络问题

(反馈的按钮忘记加了  我下个版本补一下...

**Comment by lethefrost** [comment]
> * 接口失效了
> * 高频请求  被服务器暂时屏蔽了
> * 不支持
> * 检查更新  最新版本  Version 0.4.5 (19022812)
> * 网络问题
> 
> (反馈的按钮忘记加了 我下个版本补一下...

b站动态能刷出来，但是直接用链接或者点进去之后自动跳转的链接就一直“ಠ_ಠoops”了。
奇怪的是，今天好了……，谢谢_(┐「ε:)_

**Comment by lethefrost** [comment]
诶，音轨还是抓不到(゜-゜)

**Comment by xjbeta** [comment]
是不是被你静音了...
提供下av 号?
B站主站  除了比较旧的视频解析会有问题  应该不会解析不出

**Comment by lethefrost** [comment]
> 是不是被你静音了...
> 提供下av 号?
> B站主站 除了比较旧的视频解析会有问题 (番剧不支持) 应该不会解析不出

![image](https://user-images.githubusercontent.com/47198693/55852826-791ad100-5b2c-11e9-9006-cf4b94e4e21f.png)
这个仿佛是日常抽风……？大于一半的概率啥也打不开，过了一阵看有时候就好了。
我觉得不是因为被我静音了，因为我打开了iina的音轨，看到音轨显示为无。
![image](https://user-images.githubusercontent.com/47198693/55852924-ddd62b80-5b2c-11e9-89f7-d678f6227486.png)
无论哪个AV号都这样诶，是bug吗？
说起来，选清晰度那里会稍微卡一小会，一开始不知道是单击按钮的操作，双击结果一连打开了两个iina……如果在卡的过程中再去点，会打开好多个iina……

**Comment by lethefrost** [comment]
因为至今没成功看过整个视频，不太确定弹幕有没有抓到，但从目前的情况看起来，弹幕也是没有的(゜-゜)

**Comment by xjbeta** [comment]
应用内重现一遍操作  然后进这个目录  把log 发出来看看
`~/⁨Library⁩/⁨Application Support⁩⁩/⁨com.xjbeta.iina-plus⁩/iina+.log`
B站主站 选清晰度卡一下  是在下载弹幕...

**Comment by lethefrost** [comment]
> 应用内重现一遍操作 然后进这个目录 把log 发出来看看
> `~/⁨Library⁩/⁨Application Support⁩⁩/⁨com.xjbeta.iina-plus⁩/iina+.log`
> B站主站 选清晰度卡一下 是在下载弹幕...

好，但是确实没有弹幕。另外个人感觉在下载等待期间锁住按键交互比较好，以防手滑打开多个窗口……
[iina+.log](https://github.com/xjbeta/iina-plus/files/3062290/iina%2B.log)

**Comment by xjbeta** [comment]
log 内解析出来的链接能播放有声音  时间长短也和原视频相同
视频本身没有弹幕

**Comment by xjbeta** [comment]
偷懒就没写  我下个版本补上...

**Comment by lethefrost** [comment]
> log 内解析出来的链接能播放有声音 时间长短也和原视频相同
> 视频本身没有弹幕

但是其他视频也没弹幕哎，而且在iina中的情况确实如我之前截图里一样，没有音轨，好奇怪，可能是我电脑上出了什么问题？

**Comment by lethefrost** [comment]
> 偷懒就没写 我下个版本补上...

谢谢作者大大ヽ(●´∀`●)ﾉ

**Comment by xjbeta** [comment]
想起来了  你更新一下弹幕版的IINA  音频接口是我自己加上去的
IINA 本身的命令行  加不上音频
下载安装build 6  应该就可以了
https://github.com/xjbeta/iina-danmaku/releases

**Comment by lethefrost** [comment]
> 想起来了 你更新一下弹幕版的IINA 音频接口是我自己加上去的
> IINA 本身的命令行 加不上音频
> 下载安装build 6 应该就可以了
> https://github.com/xjbeta/iina-danmaku/releases

有声音了也有弹幕了！谢谢！
想问一下弹幕的缓存地址？

**Comment by xjbeta** [comment]
`/Applications/iina+.app/Contents/Resources/danmaku/iina-plus-danmaku.xml`

**Comment by lethefrost** [comment]
> /Applications/iina+.app/Contents/Resources/danmaku/iina-plus-danmaku.xml

十分感谢大大的开发！
