### ISSUE TITLE
最新版0.6.16无法加载b站视频合集

### ISSUE THREAD

**Issue by AjianYo** [xjbeta/iina-plus#160]
之前还能识别b站合集，更新0.6.16后就没用了，请问这是什么问题？

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by xjbeta** [comment]
合集还没做  只有旧的分p是可以识别的

**Comment by xjbeta** [comment]
已支持合集视频的解析
