### ISSUE TITLE
【BUG】长期不关内存占用贼高

### ISSUE THREAD

**Issue by lowking** [xjbeta/iina-plus#164]
![image](https://user-images.githubusercontent.com/33308659/181216237-338987dd-138f-452a-98bb-889d937d22b1.png)
几天不关，今天电脑感觉有点卡，看了下这内存也占用太高了
[IINA+.log](https://github.com/xjbeta/iina-plus/files/9197088/IINA%2B.log)

**Comment by xjbeta** [comment]
log 看着没什么问题  可能是内置的flv.js 播放器漏了
建议还是使用IINA(

**Comment by lowking** [comment]
> log 看着没什么问题 可能是内置的flv.js 播放器漏了 建议还是使用IINA(

边用iina看，边idea写代码，会导致kernel_task的cpu占用超高，关掉iina就好了😂虽然其他的应用占用不高
用flv.js看的话就正常多了。。。我还是定期重启iina+吧
![image](https://user-images.githubusercontent.com/33308659/181477437-9832ea1a-e513-4a06-8b6b-08b72208ad55.png)

**Comment by lowking** [comment]
只用iina播放，这段时间一直没问题，可以确定就是flv.js问题了
