### ISSUE TITLE
B站视频合集展示建议

### ISSUE THREAD

**Issue by zwzheng45** [xjbeta/iina-plus#168]
能展示合集视频已经是个很棒的功能了，但是希望能够像分p视频和番剧一样能够将当前链接的视频置顶，或者是干脆给一个视频合集的开关。否则长合集是真的很难找
<img width="350" alt="截屏2022-09-05 13 57 38" src="https://user-images.githubusercontent.com/62459108/188458641-b4e7473f-3f9e-47c3-869b-84cbf0ca3b3c.png"><img width="350" alt="截屏2022-09-05 14 17 24" src="https://user-images.githubusercontent.com/62459108/188458737-c931f77b-8247-40d4-8a72-25ab0b036e8a.png">

**Comment by xjbeta** [comment]
写了  但  下版本更新

**Comment by zwzheng45** [comment]
好的，谢谢大佬了！
