### ISSUE TITLE
🔴 打开多个「哔哩哔哩」直播间会开启多个「IINA」应用

### ISSUE THREAD

**Issue by Thomas-Harrell** [xjbeta/iina-plus#169]
+ 打开多个「哔哩哔哩」直播间会导致开启多个「IINA」应用

+ 打开多个其他平台的（斗鱼、虎牙）直播间，则只会开启同一个「IINA」应用下的多个窗口

+ IINA+ 和 IINA 均为最新版本

![SCR-20220913-ljg](https://user-images.githubusercontent.com/106761803/189839179-173cf900-485e-47b0-8148-72db701454dc.png)

**Comment by xjbeta** [comment]
换用弹幕版IINA 或者插件版IINA
https://github.com/xjbeta/iina-danmaku/releases
B站的视频和音频是分离的  但IINA 本身的接口问题  导致只能重开一个IINA 才能加载音频
