### ISSUE TITLE
IINA 无法打开直播

### ISSUE THREAD

**Issue by xjbeta** [xjbeta/iina-plus#176]
[IINA+.log](https://github.com/xjbeta/iina-plus/files/10425875/IINA%2B.log)
[iina.log](https://github.com/xjbeta/iina-plus/files/10425876/iina.log)
[mpv.log](https://github.com/xjbeta/iina-plus/files/10425877/mpv.log)
一开始能用iina能打开，后打不开了。。。

_Originally posted by @c373760488 in https://github.com/xjbeta/iina-plus/issues/129#issuecomment-1384006734_

**Comment by c373760488** [comment]
没安插件。。。。安装iina/plugin-online-media吗

**Comment by xjbeta** [comment]
https://github.com/xjbeta/iina-plugin-danmaku/releases/latest
下载 .iinaplgz 文件
IINA 设置  插件 从本地包安装  选中 .iinaplgz  之后重启

**Comment by xjbeta** [comment]
<img width="631" alt="Screen Shot 2023-01-16 at 21 19 16" src="https://user-images.githubusercontent.com/11794321/212687613-d34e863a-5812-4533-8074-f6bdf038848c.png">

插件页面如图设置  然后command + Q 退出IINA 后重新打开
