### ISSUE TITLE
如何通过命令行使用原版IINA 的插件系统

### ISSUE THREAD

**Issue by QuantumRoseinAmethystVase** [xjbeta/iina-plus#185]
请问如果用命令行开启原版IINA 的插件系统，因为我发现本项目的插件版没有Safari的扩展可用，网上搜索了很久也没有找到方法。

<img width="347" alt="image" src="https://github.com/xjbeta/iina-plus/assets/62452364/bcbcb7cf-6d4a-44e7-a205-4667702b2a87">

**Comment by xjbeta** [comment]
`defaults write com.colliderli.iina iinaEnablePluginSystem true`
原版直接用弹幕插件会有些bug  
比如打开第二个视频卡死  必需重开IINA
