### ISSUE TITLE
部分Bilibili 视频  无法解析

### ISSUE THREAD

**Issue by xjbeta** [xjbeta/iina-plus#19]
如 av50507702

**Comment by toooonyy** [comment]
可以重现，刚刚准备开个 issue 来的呢，请问可以输出 log 文件吗

**Comment by xjbeta** [comment]
av1001686  已经被删除了
旧视频可能无法解析播放链接和弹幕
因为用的旧的API  (不清楚B 站   换接口有没有全换到新的来
