### ISSUE TITLE
macOS Sonoma打开iina-plugin v1.3.2意外退出

### ISSUE THREAD

**Issue by QuantumRoseinAmethystVase** [xjbeta/iina-plus#190]
- 系统：macOS 14 Sonoma beta 3
安装iina-plugin v1.3.2后打开会显示意外退出。v1.3.1可以正常安装。

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/libjxl.0.8.dylib
Referenced from: <5FFF1E04-F8F6-33FB-98D4-85CFFE347B77> /Applications/IINA.app/Contents/Frameworks/libavformat.60.dylib
Reason: tried: '/usr/lib/swift/libjxl.0.8.dylib' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/libjxl.0.8.dylib' (no such file), '/Applications/IINA.app/Contents/Frameworks/libjxl.0.8.dylib' (no such file), '/usr/lib/swift/libjxl.0.8.dylib' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/libjxl.0.8.dylib' (no such file), '/Applications/IINA.app/Contents/Frameworks/libjxl.0.8.dylib' (no such file), '/usr/local/lib/libjxl.0.8.dylib' (no such file), '/usr/lib/libjxl.0.8.dylib' (no such file, not in dyld cache)Library not loaded: @rpath/libjxl.0.8.dylib
Referenced from: <C350E626-4191-3649-AE45-EB524F33A58F> /Applications/IINA.app/Contents/Frameworks/libavcodec.60.dylib
Reason: tried: '/usr/lib/swift/libjxl.0.8.dylib' (no such file, not in dyld cache), '/System/Vol
(terminated at launch; ignore backtrace)

**Comment by KenChen1998** [comment]
同样的问题 请问你解决了吗

**Comment by xjbeta** [comment]
重新编译了一份  试试还有没有问题
下版本更新会换回原版IINA   还是不行的话不会解决
[IINA (mega)](https://mega.nz/file/M1ECETTT#Ke4CtP-otjs_sGDqXMbtpQEyfpf63OeaaVv4chF0fto)

**Comment by KenChen1998** [comment]
> 重新编译了一份 试试还有没有问题 下版本更新会换回原版IINA 还是不行的话不会解决 [IINA (mega)](https://mega.nz/file/M1ECETTT#Ke4CtP-otjs_sGDqXMbtpQEyfpf63OeaaVv4chF0fto)

这个可以用 非常感谢

**Comment by QuantumRoseinAmethystVase** [comment]
> 重新编译了一份 试试还有没有问题 下版本更新会换回原版IINA 还是不行的话不会解决 [ 伊纳 (巨型)](https://mega.nz/file/M1ECETTT#Ke4CtP-otjs_sGDqXMbtpQEyfpf63OeaaVv4chF0fto)

已解决，此版本可行👍
