### ISSUE TITLE
无法安装插件，点击install没有反应

### ISSUE THREAD

**Issue by reveever** [xjbeta/iina-plus#196]
尝试全部删除后重新安装，点击 install 没有任何反应...
也没有相关的错误日志..

<img width="1067" alt="屏幕快照 2023-07-31 01 23 17" src="https://github.com/xjbeta/iina-plus/assets/9657612/11a12053-9ec4-4a90-bdf7-a266344bf517">

macOS 10.14.6
IINA+ 0.7.2 (23072611)
IINA 1.3.3 Build 138

**Comment by xjbeta** [comment]
fixed aa5b76e
