### ISSUE TITLE
无法更新插件

### ISSUE THREAD

**Issue by xjbeta** [xjbeta/iina-plus#197]
启用插件步骤无法完成，点击Update 0.1.7 to 0.1.8 按钮没反应，所以没办法进行到第三部
![image](https://github.com/xjbeta/iina-plus/assets/10734951/69d3d3b3-562e-4eb2-b64b-ea869e8a9edd)

_Originally posted by @GEEKTEDDY in https://github.com/xjbeta/iina-plus/issues/194#issuecomment-1659721434_

**Comment by xjbeta** [comment]
Command+Q 重启IINA+
进入设置点一次更新按钮
帮助 - 日志文件  复制内容发出来看看

**Comment by gernal-blind** [comment]
同样的问题
<img width="1151" alt="image" src="https://github.com/xjbeta/iina-plus/assets/55597586/4293e761-0637-4c7c-9ceb-3d70eb4e936b">

**Comment by xjbeta** [comment]
0.7.3 已修复
