### ISSUE TITLE
iina-plus 1.3.0弹幕版本，可以看抖音直播吗？

### ISSUE THREAD

**Issue by smile-wind** [xjbeta/iina-plus#198]
麻烦问下，怎么观看抖音直播呢，目前虎牙和斗鱼都可以正常观看，直接添加url地址然后解析就好；然后在抖音找了个直播间把地址（live.douyin.com/xxxxxx）添加进iina+提示无法解析，请教下该如何操作，谢谢

**Comment by xjbeta** [comment]
`https://live.douyin.com/703335576677`
参考直播链接  没有任何问题

**Comment by PengOvO** [comment]
> `https://live.douyin.com/703335576677` 参考直播链接没有任何问题
确实昨天开始,所有的抖音直播都无法解析,集体显示灰色。斗鱼和虎牙的直播一切正常。

烦请大佬看下是不是哪里出错了，谢谢，辛苦了！

**Comment by xjbeta** [comment]
`Command + Q`  重启IINA+  
双击解析一个抖音直播间  等转完圈 
屏幕左上靠中间  帮助 / 日志文件  发来看看

抖音直播  稳定性存在一定问题  重开应用初始化可能会失败
暂时建议添加3个及以上直播间  重开IINA+ 的时候  用`Command + R` 刷新两次来触发`失败重试`

**Comment by smile-wind** [comment]
> `Command + Q`  重启IINA+  
> 双击解析一个抖音直播间  等转完圈 
> 屏幕左上靠中间  帮助 / 日志文件  发来看看
> 
> 抖音直播  稳定性存在一定问题  重开应用初始化可能会失败
> 暂时建议添加3个及以上的抖音直播间  重开IINA+ 的时候  用`Command + R` 刷新两次来触发`失败重试`

 > 日志截图如下，测试添加3个及以上直播间也是无法解析抖音直播地址

> 双击解析抖音的，一直在转圈，无法解析完成，日志可能不完整

![mmexport1691469087289.png](https://github.com/xjbeta/iina-plus/assets/23187087/c795cb8f-9ad9-4cae-9086-344f491526f7)

**Comment by smile-wind** [comment]
####  补充一下目前使用的版本

> IINA-PLUS  如下图

![mmexport1691469071810.png](https://github.com/xjbeta/iina-plus/assets/23187087/ce15b30f-f4f0-49d3-8f26-1b3b8630bba7)

> IINA 播放器，如下图
![mmexport1691469075151.png](https://github.com/xjbeta/iina-plus/assets/23187087/d8e60d8c-fd77-4bf8-b9a5-87a7325b9fc8)

> MacOS  系统为 Big Sur 11.3.1

> 添加抖音地址后，主界面显示图
![mmexport1691469077935.png](https://github.com/xjbeta/iina-plus/assets/23187087/05e1a946-869e-4517-9153-8334b8727437)

> 双击解析抖音地址显示图
![mmexport1691469083944.png](https://github.com/xjbeta/iina-plus/assets/23187087/953d8786-046c-4d1c-a121-26f3b162dd56)

> 另外也试过`command+q`大退，然后重新刷新或者添加，同样无法解析

> 感谢开发者的回复，是不是我的版本或设置问题，谢谢

**Comment by xjbeta** [comment]
[IINA+.app.zip](https://github.com/xjbeta/iina-plus/files/12288923/IINA%2B.app.zip)
重写了一部分抖音的解析  试试修好没

**Comment by PengOvO** [comment]
> [IINA+.app.zip](https://github.com/xjbeta/iina-plus/files/12288923/IINA%2B.app.zip) 重写了一部分抖音的解析 试试修好没

这个版本可以解析出抖音直播状态和直播画面，但是没有直播弹幕。

内置flv.js：
<img width="650" alt="Snipaste_2023-08-08_16-26-22" src="https://github.com/xjbeta/iina-plus/assets/80612282/9b93498d-4900-48cb-9ebf-bf63ffff163e">

IINA 1.3.2 :
<img width="650" alt="Snipaste_2023-08-08_16-30-01" src="https://github.com/xjbeta/iina-plus/assets/80612282/7993e1ae-1edb-4942-a690-d94340f8d1da">

MacOS 系统为 Big Sur 11.2.3

烦请大佬看下，谢谢，辛苦了！

**Comment by xjbeta** [comment]
[IINA+.app.zip](https://github.com/xjbeta/iina-plus/files/12289601/IINA%2B.app.zip)
再试试  只测试IINA 就行

**Comment by smile-wind** [comment]
> [IINA+.app.zip](https://github.com/xjbeta/iina-plus/files/12289601/IINA%2B.app.zip)
> 再试试  只测试IINA 就行

##### 感谢感谢，使用这个版本的IINA+，抖音的直播解析和弹幕都可以正常观看，再次感谢😊

**Comment by smile-wind** [comment]
再次感谢
