### ISSUE TITLE
Not showing text on macOS Mojave developer beta7

### ISSUE THREAD

**Issue by CaptainYukinoshitaHachiman** [xjbeta/iina-plus#2]
As the tittle, the texts are not showing.

Maybe you should consider to file a bug at Bug Reporter

<img width="517" alt="screen shot 2018-08-15 at 4 38 14 pm" src="https://user-images.githubusercontent.com/25654046/44139531-ec37b498-a0a9-11e8-8325-583ff8959f9e.png">

[Log file](https://github.com/xjbeta/iina-plus/files/2289680/iina%2B.log) is attached.

**Comment by xjbeta** [comment]
Nothing tested on Mojave.

**Comment by CaptainYukinoshitaHachiman** [comment]
Well, I tried switching back to Light Mode and then everything was correctly showing. I checked your code and found the colors are not correctly configured for Dark Mode.

I personally suggest you to watch the following sessions of WWDC18 to adapt iina+ for Dark Mode. 
[Introducing Dark Mode](https://developer.apple.com/videos/play/wwdc2018/210/)
[Advanced Dark Mode](https://developer.apple.com/videos/play/wwdc2018/218/)

**Comment by CaptainYukinoshitaHachiman** [comment]
It's fixed so now we can close this issue.
