### ISSUE TITLE
解析时允许传入 cookies？

### ISSUE THREAD

**Issue by toooonyy** [xjbeta/iina-plus#20]
希望可以导入 cookies（类似 `you-get -c cookies.txt`）这样的参数

**Comment by xjbeta** [comment]
直播用不到cookies
B站主站在设置里登陆后会使用cookies 解析
A站我不怎么用
还有什么用得到cookies 的地方吗?

**Comment by toooonyy** [comment]
啊，其实主要就是想要 b 站的 1080p60。原来登陆之后会用的吗
