### ISSUE TITLE
斗鱼失效

### ISSUE THREAD

**Issue by SherlockedTxh** [xjbeta/iina-plus#21]
14:51:38.685 [iina][d] App will launch
14:51:38.685 [iina][d] Got arguments ["https://tc-tct.douyucdn2.cn/dyliveflv1a/93589rYrLgOpduUo_1024p.flv?wsAuth=4f2afc331a93a0a48c1d21dafee3eb43&token=web-h5-0-93589-deafe2c3c344fd0ef8090e263f280c54df122b3d5c1d618c&logo=0&expire=0&did=94cc5199006a8d940de2b5ac00081501&ver=Douyu_219021902&pt=2&st=0&mix=0&isp=", "--mpv-force-media-title=异灵术：欢迎来到冷冰冰的直播间", "--mpv-ytdl=no"]
14:51:38.686 [iina][d] IINA arguments: ["--mpv-force-media-title=异灵术：欢迎来到冷冰冰的直播间", "--mpv-ytdl=no"]
14:51:38.686 [iina][d] Filenames from arguments: ["https://tc-tct.douyucdn2.cn/dyliveflv1a/93589rYrLgOpduUo_1024p.flv?wsAuth=4f2afc331a93a0a48c1d21dafee3eb43&token=web-h5-0-93589-deafe2c3c344fd0ef8090e263f280c54df122b3d5c1d618c&logo=0&expire=0&did=94cc5199006a8d940de2b5ac00081501&ver=Douyu_219021902&pt=2&st=0&mix=0&isp="]
14:51:38.717 [iina][d] App launched
14:51:38.718 [iina][d] Loading key bindings
14:51:38.721 [iina][d] Set key bindings
14:51:38.790 [iina][d] Setting up MediaPlayer integration
14:51:38.815 [player0][d] Set path to /Applications/IINA.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
14:51:38.815 [player0][d] Set http_proxy to 0.0.0.0:8888
14:51:38.827 [player0][d] Track list changed
14:51:38.831 [player0][d] Track list changed
14:51:38.833 [player0][d] Open URL: https://tc-tct.douyucdn2.cn/dyliveflv1a/93589rYrLgOpduUo_1024p.flv?wsAuth=4f2afc331a93a0a48c1d21dafee3eb43&token=web-h5-0-93589-deafe2c3c344fd0ef8090e263f280c54df122b3d5c1d618c&logo=0&expire=0&did=94cc5199006a8d940de2b5ac00081501&ver=Douyu_219021902&pt=2&st=0&mix=0&isp=
14:51:38.833 [player0][d] Opening https://tc-tct.douyucdn2.cn/dyliveflv1a/93589rYrLgOpduUo_1024p.flv?wsAuth=4f2afc331a93a0a48c1d21dafee3eb43&token=web-h5-0-93589-deafe2c3c344fd0ef8090e263f280c54df122b3d5c1d618c&logo=0&expire=0&did=94cc5199006a8d940de2b5ac00081501&ver=Douyu_219021902&pt=2&st=0&mix=0&isp= in main window
14:51:38.998 [iina][d] Falling back to nominal display refresh rate: 60.00082845465592 from 0.0
14:51:39.018 [player0][d] File started
14:51:39.018 [player0][d] Track list changed
14:51:39.018 [player0][d] Started auto load
14:51:39.018 [iina][w] mpv log: [cplayer] warn: Sending hook command failed. Removing hook.
14:51:39.018 [fmatcher][d] **Start matching
14:51:59.863 [player0][d] Write watch later config
14:51:59.868 [iina][w] mpv log: [ffmpeg] error: NULL: Invalid NAL unit size (288149 > 80962).
14:51:59.868 [iina][d] App should terminate
14:51:59.868 [iina][w] mpv log: [ffmpeg] error: NULL: missing picture in access unit with size 81037
14:51:59.868 [player0][d] Write watch later config
14:51:59.869 [iina][w] mpv log: [ffmpeg/video] error: h264: Invalid NAL unit size (288149 > 80962).
14:51:59.869 [iina][w] mpv log: [ffmpeg/video] error: h264: Error splitting the input into NAL units.
14:51:59.869 [iina][w] mpv log: [ffmpeg/demuxer] warn: flv: Could not find codec parameters for stream 0 (Audio: aac, 44100 Hz, stereo, 131 kb/s): unspecified sample format
14:51:59.869 [iina][w] mpv log: [ffmpeg/demuxer] warn: Consider increasing the value for the 'analyzeduration' and 'probesize' options
14:51:59.869 [iina][w] mpv log: [ffmpeg/demuxer] warn: flv: Could not find codec parameters for stream 1 (Video: h264, none, 3072 kb/s): unspecified size
14:51:59.869 [iina][w] mpv log: [ffmpeg/demuxer] warn: Consider increasing the value for the 'analyzeduration' and 'probesize' options
14:51:59.870 [iina][d] App will terminate

**Comment by xjbeta** [comment]
解析出来的链接没有问题
把IINA 的代理关了?

**Comment by SherlockedTxh** [comment]
> 解析出来的链接没有问题
> 把IINA 的代理关了?

代理关了就好了，谢谢！
