### ISSUE TITLE
iina打开斗鱼怎么更改fps 默认的fps60会使电脑温度上升

### ISSUE THREAD

**Issue by Joshuayuuu** [xjbeta/iina-plus#210]

**Comment by Joshuayuuu** [comment]
我排查了一下 似乎是因为斗鱼原画下我的比特率高 从而温度高 不知道有什么办法能解决

**Comment by xjbeta** [comment]
看低码率的直播  或者
换用内置的flv.js (mpegts.js)播放器来看直播  能缓解一些  (mpv 新版本性能没旧版好
