### ISSUE TITLE
抖音直播 解析不了 macos11.7.10系统。是因为低版本系统导致的吗

### ISSUE THREAD

**Issue by dailul** [xjbeta/iina-plus#213]
<img width="535" alt="image" src="https://github.com/xjbeta/iina-plus/assets/32507021/3a4920cd-9e17-42cb-9e47-2b4f065cbb3d">

**Comment by dailul** [comment]
可能真是系统原因，升级 macos12系统后 抖音直播可以正常解析了

**Comment by xjbeta** [comment]
0.7.15 换用了一个新的API 可能解决了旧版系统解析不了抖音的问题
