### ISSUE TITLE
更新到0.8.0后无法显示弹幕

### ISSUE THREAD

**Issue by xiaoshu-lin** [xjbeta/iina-plus#229]
如题，试了一下重新安装0.7.30后弹幕可以正常显示

**Comment by xjbeta** [comment]
已修复 7341b61

**Comment by xiaoshu-lin** [comment]
> 已修复 [7341b61](https://github.com/xjbeta/iina-plus/commit/7341b61fb753b618602418ee4bad3e9e61c9adff)

请问下发布了吗，我刚刚下载了release里的0.8.0dmg文件，还是没有弹幕。

**Comment by xjbeta** [comment]
还没发release

**Comment by xiaoshu-lin** [comment]
> 还没发release

哦哦，好的。
另外更新到0.8.0后也无法打卡B站的直播，提示：

> VideoDecoder.swift[82], prepareDanmakuFile(yougetJSON:id:): Ignore Danmaku download.
MainViewController.swift[696], open(result:row:): Open result with plugin
Processes.swift[153], openWithPlayer(_:_:): Not Found YouGetJSON Url.

**Comment by xjbeta** [comment]
全部打不开  还是某些打不开  发个直播的链接来看看

**Comment by xiaoshu-lin** [comment]
> 全部打不开 还是某些打不开 发个直播的链接来看看

我反正试了两个都打不开：

- https://live.bilibili.com/22747736
- https://live.bilibili.com/7734200

**Comment by xjbeta** [comment]
无法重现  都可以正常解析播放

**Comment by xjbeta** [comment]
试试在设置里  用flv.js 来打开直播    用的是另一套api 接口  可能有用

**Comment by xiaoshu-lin** [comment]
> 试试在设置里 用flv.js 来打开直播 用的是另一套api 接口 可能有用

这样是可以打开的。

**Comment by xjbeta** [comment]
设置里登录B站账号了吗  可能是新API 必须登录  才能获取到全部的清晰度

**Comment by xiaoshu-lin** [comment]
> 设置里登录B站账号了吗 可能是新API 必须登录 才能获取到全部的清晰度

确实，登录了账号就好了。
