### ISSUE TITLE
在 iina nightly 上不可用

### ISSUE THREAD

**Issue by rainlycoris** [xjbeta/iina-plus#230]
在 https://github.com/iina/iina/actions/runs/9605819685 及以后不可用

iina 0.8.0 macos sonoma 14.5

<img width="372" alt="截屏2024-08-08 16 28 41" src="https://github.com/user-attachments/assets/6213b6ff-a921-4f69-b729-7e8ece8c296e">

请问我该怎么解决这个问题，非常感谢（

**Comment by xjbeta** [comment]
已修复  更新本体到0.8.1  然后在设置里更新插件到0.1.9
