### ISSUE TITLE
Bilibili上分P的视频无法解析

### ISSUE THREAD

**Issue by ATH733** [xjbeta/iina-plus#29]
如图所示，可以正常的解析目录，但是具体到某一P就无法播放。尝试了数个视频都是如此。
<img width="612" alt="屏幕快照 2019-07-05 下午6 13 52" src="https://user-images.githubusercontent.com/52399579/60715928-c30b2b80-9f50-11e9-8448-758f197a33e0.png">
<img width="612" alt="屏幕快照 2019-07-05 下午6 14 00" src="https://user-images.githubusercontent.com/52399579/60715933-c43c5880-9f50-11e9-89e0-caa2f437bfd4.png">

**Comment by xjbeta** [comment]
因为之前视频解析的接口有改动  大部分旧投稿  都不支持了
