### ISSUE TITLE
最新版斗鱼弹幕连接失效

### ISSUE THREAD

**Issue by oero** [xjbeta/iina-plus#37]
AppDelegate.swift[35], applicationDidFinishLaunching(_:): App did finish launch
AppDelegate.swift[38], applicationDidFinishLaunching(_:): App Version 0.4.8 (Build 19092315)
AppDelegate.swift[39], applicationDidFinishLaunching(_:): macOS 版本 10.14.6（版号 18G84）
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
AppDelegate.swift[41], applicationDidFinishLaunching(_:): 35.3 MB
MainViewController.swift[426], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
MainViewController.swift[426], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
ImageLoader.swift[65], removeAll(): Remove all image cache error.
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
ImageLoader.swift[65], removeAll(): Remove all image cache error.
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
ImageLoader.swift[65], removeAll(): Remove all image cache error.
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
ImageLoader.swift[65], removeAll(): Remove all image cache error.
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
ImageLoader.swift[65], removeAll(): Remove all image cache error.
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
ImageLoader.swift[65], removeAll(): Remove all image cache error.
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
ImageLoader.swift[65], removeAll(): Remove all image cache error.
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
ImageLoader.swift[65], removeAll(): Remove all image cache error.
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
ImageLoader.swift[65], removeAll(): Remove all image cache error.
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
ImageLoader.swift[65], removeAll(): Remove all image cache error.
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
ImageLoader.swift[65], removeAll(): Remove all image cache error.
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
ImageLoader.swift[65], removeAll(): Remove all image cache error.
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
ImageLoader.swift[65], removeAll(): Remove all image cache error.
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
ImageLoader.swift[65], removeAll(): Remove all image cache error.
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
ImageLoader.swift[65], removeAll(): Remove all image cache error.
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
MainViewController.swift[426], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
MainViewController.swift[121], decodeUrl(): isNotLiving
MainViewController.swift[121], decodeUrl(): douyuNotFoundRoomId
MainViewController.swift[121], decodeUrl(): douyuNotFoundRoomId
MainViewController.swift[121], decodeUrl(): douyuNotFoundRoomId
MainViewController.swift[121], decodeUrl(): douyuNotFoundRoomId
MainViewController.swift[121], decodeUrl(): isNotLiving
Processes.swift[216], openWithPlayer(_:audioUrl:title:options:): Player arguments: ["https://pcdn-a1.douyucdn.cn/live/63136rqMyUeGV4lv_4000.flv?wsAuth=6c3b7b5af55da772baf141c10aba3980&token=web-h5-0-63136-9e54c9676954f9967120155d3f822a82902fda7c8ccfe7e4&logo=0&expire=0&did=f72ad9a1bd4ff330d5b2b89a00031501&ver=Douyu_219042402&pt=2&st=0&origin=all&mix=0&isp=", "--mpv-force-media-title=我太难了~ 63136", "--mpv-ytdl=no"]
MainViewController.swift[426], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
MainViewController.swift[426], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
MainViewController.swift[426], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
MainViewController.swift[426], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
Processes.swift[216], openWithPlayer(_:audioUrl:title:options:): Player arguments: ["https://pcdn-a1.douyucdn.cn/live/63136rqMyUeGV4lv_4000.flv?wsAuth=56966629daacf544625cb7711e1af3d9&token=web-h5-0-63136-9e54c9676954f996c991bcd749cafb8909be3da0a9aac1ba&logo=0&expire=0&did=88b43cf19774ce717bdc5fb600031501&ver=Douyu_219042402&pt=2&st=0&origin=all&mix=0&isp=", "--mpv-force-media-title=我太难了~ 63136", "--mpv-ytdl=no", "--danmaku"]
HttpServer.swift[40], start(): Server has started ( port = 19080 ). Try to connect now...
HttpServer.swift[27], start(): Websocket client connected.
HttpServer.swift[76], send(_:text:): WriteText to websocket: {"method":"customFont","text":"Al Bayan"}
HttpServer.swift[76], send(_:text:): WriteText to websocket: {"method":"dmSpeed","text":"556"}
HttpServer.swift[76], send(_:text:): WriteText to websocket: {"method":"dmOpacity","text":"0.5762296597633136"}
HttpServer.swift[76], send(_:text:): WriteText to websocket: {"method":"dmBlockList","text":""}
Danmaku.swift[216], initDouYuSocket(_:): douyu socket started: true
Danmaku.swift[270], initDouYuSocket(_:): Douyu socket error: Error code: -9971(0x-26F3), Connection reset by peer
Danmaku.swift[308], startTimer(): send keep live pack error: Error code: -9980(0x-26FC), Broken pipe
HttpServer.swift[33], start(): Websocket client disconnected.
MainViewController.swift[426], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
Processes.swift[216], openWithPlayer(_:audioUrl:title:options:): Player arguments: ["https://tc-tct.douyucdn2.cn/dyliveflv3/3374504roev3caBN.flv?wsAuth=c0603dd15d9e81b14b5b139a1e2058f8&token=web-h5-0-3374504-1f9ce6705dbb484b5a1286a2e83e6a30a7723e4b8352a924&logo=0&expire=0&did=d28b27097ed394aa14ffb9ff00031501&ver=Douyu_219042402&pt=2&st=0&origin=ws&mix=1&isp=", "--mpv-force-media-title=在家也是小可爱", "--mpv-ytdl=no", "--danmaku"]
HttpServer.swift[40], start(): Server has started ( port = 19080 ). Try to connect now...
HttpServer.swift[27], start(): Websocket client connected.
HttpServer.swift[76], send(_:text:): WriteText to websocket: {"method":"customFont","text":"Al Bayan"}
HttpServer.swift[76], send(_:text:): WriteText to websocket: {"method":"dmSpeed","text":"556"}
HttpServer.swift[76], send(_:text:): WriteText to websocket: {"method":"dmOpacity","text":"0.5762296597633136"}
HttpServer.swift[76], send(_:text:): WriteText to websocket: {"method":"dmBlockList","text":""}
Danmaku.swift[216], initDouYuSocket(_:): douyu socket started: true
Danmaku.swift[270], initDouYuSocket(_:): Douyu socket error: Error code: -9971(0x-26F3), Connection reset by peer
Danmaku.swift[308], startTimer(): send keep live pack error: Error code: -9980(0x-26FC), Broken pipe
HttpServer.swift[33], start(): Websocket client disconnected.
MainViewController.swift[426], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
MainViewController.swift[121], decodeUrl(): douyuNotFoundRoomId
MainViewController.swift[121], decodeUrl(): douyuNotFoundRoomId
MainViewController.swift[121], decodeUrl(): douyuNotFoundRoomId
MainViewController.swift[121], decodeUrl(): douyuNotFoundRoomId
MainViewController.swift[121], decodeUrl(): isNotLiving
MainViewController.swift[121], decodeUrl(): isNotLiving
Processes.swift[216], openWithPlayer(_:audioUrl:title:options:): Player arguments: ["https://pcdn-a1.douyucdn.cn/live/63136rqMyUeGV4lv_4000.flv?wsAuth=b7fc109569378a62f829f9fc28608ec0&token=web-h5-0-63136-9e54c9676954f996b60c56301ca3eab59ee41201b0e34410&logo=0&expire=0&did=5ff2759b4bd9ff2b25c7713400031501&ver=Douyu_219042402&pt=2&st=0&origin=all&mix=0&isp=", "--mpv-force-media-title=我太难了~ 63136", "--mpv-ytdl=no", "--danmaku"]
HttpServer.swift[40], start(): Server has started ( port = 19080 ). Try to connect now...
HttpServer.swift[27], start(): Websocket client connected.
HttpServer.swift[76], send(_:text:): WriteText to websocket: {"method":"customFont","text":"Al Bayan"}
HttpServer.swift[76], send(_:text:): WriteText to websocket: {"method":"dmSpeed","text":"556"}
HttpServer.swift[76], send(_:text:): WriteText to websocket: {"method":"dmOpacity","text":"0.5762296597633136"}
HttpServer.swift[76], send(_:text:): WriteText to websocket: {"method":"dmBlockList","text":""}
Danmaku.swift[270], initDouYuSocket(_:): Douyu socket error: Error code: -9989(0x-2705), Operation timed out
MainViewController.swift[426], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
ImageLoader.swift[65], removeAll(): Remove all image cache error.
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
ImageLoader.swift[65], removeAll(): Remove all image cache error.
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
MainViewController.swift[426], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
HttpServer.swift[33], start(): Websocket client disconnected.
MainViewController.swift[426], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
MainViewController.swift[426], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
MainViewController.swift[121], decodeUrl(): douyuNotFoundRoomId
MainViewController.swift[121], decodeUrl(): douyuNotFoundRoomId
MainViewController.swift[121], decodeUrl(): isNotLiving
MainViewController.swift[121], decodeUrl(): douyuNotFoundRoomId
MainViewController.swift[121], decodeUrl(): douyuNotFoundRoomId
MainViewController.swift[121], decodeUrl(): isNotLiving
Processes.swift[216], openWithPlayer(_:audioUrl:title:options:): Player arguments: ["https://pcdn-a1.douyucdn.cn/live/63136rqMyUeGV4lv_4000.flv?wsAuth=20b58686c67c5cdcb3a8525dbf57576a&token=web-h5-0-63136-9e54c9676954f996db0b3dc72fb652ed400a3e57bfbddca7&logo=0&expire=0&did=2cb9ec5c3d4893293670e46500031501&ver=Douyu_219042402&pt=2&st=0&origin=all&mix=0&isp=", "--mpv-force-media-title=我太难了~ 63136", "--mpv-ytdl=no", "--danmaku"]
HttpServer.swift[40], start(): Server has started ( port = 19080 ). Try to connect now...
HttpServer.swift[27], start(): Websocket client connected.
HttpServer.swift[76], send(_:text:): WriteText to websocket: {"method":"customFont","text":"Al Bayan"}
HttpServer.swift[76], send(_:text:): WriteText to websocket: {"method":"dmSpeed","text":"556"}
HttpServer.swift[76], send(_:text:): WriteText to websocket: {"method":"dmOpacity","text":"0.5762296597633136"}
HttpServer.swift[76], send(_:text:): WriteText to websocket: {"method":"dmBlockList","text":""}
MainViewController.swift[426], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
MainViewController.swift[426], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
HttpServer.swift[33], start(): Websocket client disconnected.
MainViewController.swift[426], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
MainViewController.swift[426], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
Danmaku.swift[270], initDouYuSocket(_:): Douyu socket error: Error code: -9989(0x-2705), Operation timed out
MainViewController.swift[426], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
MainViewController.swift[426], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
ImageLoader.swift[43], cacheSize(): file:///Users/oreo/Library/Caches/com.xjbeta.iina-plus/
MainViewController.swift[426], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid

昨天更新了最新版才出现的问题

**Comment by oero** [comment]
还有缓存清理按钮也是无效，按了没反应，缓存永远是这个大小

**Comment by xjbeta** [comment]
斗鱼弹幕失效无法重现  应该只是短时间抽搐
0.4.8 (19092315) 占空间的图片缓存不在硬盘里  剩下的缓存是些别的   下版本回调
