### ISSUE TITLE
Cannot watch bangumi on bilibili in IINA

### ISSUE THREAD

**Issue by CaptainYukinoshitaHachiman** [xjbeta/iina-plus#4]
It seems IINA+ cannot open banugmi on bilibili in IINA. It fetches the urls correctly just as what the you-get with command-line interface does, however IINA seems to be not responding to it.

A [video](https://youtu.be/kVIyDyKw6dI) is attached for demo.

**Comment by xjbeta** [comment]
IINA didn't support open a edl link or "merge-files".
https://github.com/lhc70000/iina/pull/1911

**Comment by legendtang** [comment]
What is the current status for this support?

**Comment by xjbeta** [comment]
No plans to support the banugmi on bilibili.
