### ISSUE TITLE
iina+点击一次就在程序坞开一个播放器

### ISSUE THREAD

**Issue by diklios5768** [xjbeta/iina-plus#46]
用 iina+每次点击一个新的播放源，都会在程序坞新开一个播放器，不管之前的播放器是不是在播放，这样看几个视频底下全是播放器，非常不舒服。而且哔哩哔哩加载弹幕的时候，有的视频有弹幕，有的就没有，但是并没有显示未连接，也不知道是不是哪里操作不对。

**Comment by xjbeta** [comment]
只支持同一时间打开一个直播/视频  打开多个直播/视频  无法保证弹幕正常

因为是直接使用iina-cli 来打开视频  所以会打开一堆播放器
IINA - 设置 - 一般 - 没有打开的窗口时退出
勾选这个  能在IINA 没有窗口时自动退出  能变相解决吧
