### ISSUE TITLE
如果有空的话，可以添加金刚直播的支持吗，感谢，非常喜欢这个软件

### ISSUE THREAD

**Issue by mrhuangbh** [xjbeta/iina-plus#47]
网址：www.kingkong.com.tw

**Comment by mrhuangbh** [comment]
网页部分源码：{"id":4,"title":"最佳","video":"https:\u002F\u002Fvideo-tx2.lv-play.com\u002Flive\u002FxxxxxxG.flv"}（xxxx为直播间号）

直播源：https://video-tx2.lv-play.com/live/xxxxxxG.flv（xxxxxx为直播间号）

**Comment by xjbeta** [comment]
0.4.12 已支持
据说这个直播网站  会把弹幕分成'国内' 和 '国外'  两个区  所以不保证弹幕可以看到全部
有问题  可以再开新的issues

**Comment by mrhuangbh** [comment]
十分感谢🙏
