### ISSUE TITLE
关于金刚直播弹幕国内无法显示的解决办法。

### ISSUE THREAD

**Issue by mrhuangbh** [xjbeta/iina-plus#48]
国内用dns污染了金刚直播。
也许通过直接连接ip能解决无法显示弹幕问题。
下面是金刚直播的正常ip：
set a=13.226.120.101 www.kingkong.com.tw
set b=13.35.7.103 m.kingkong.com.tw
set c=13.35.7.125 static.kingkong.com.tw
set d=13.35.165.52 img.kingkong.com.tw

REM set n=13.226.120.62 api.kingkongapp.com
REM set o=* . * . * . * www.kingkongapp.com

set e=103.210.23.233 cht.ws.kingkong.com.tw
set f=23.91.101.80 cht-1.ws.kingkong.com.tw
set g=107.150.124.169 cht-2.ws.kingkong.com.tw
set h=36.255.220.6 ctl.ws.kingkong.com.tw
set i=23.91.97.192 ctl-1.ws.kingkong.com.tw
set j=103.14.33.45 ctl-2.ws.kingkong.com.tw
set k=45.249.245.27 ctl-3.ws.kingkong.com.tw
set l=103.72.146.38 ctl-4.ws.kingkong.com.tw
set m=128.1.136.140 state-1.ws.kingkong.com.tw

**Comment by xjbeta** [comment]
如果是dns 污染的话  可以试试直接修改hosts
