### ISSUE TITLE
对于alfed open in iina workflow的适配

### ISSUE THREAD

**Issue by Lemon2ee** [xjbeta/iina-plus#56]
因为iina本身的从url中播放视频功能，eutialia制作了这个workflow。

```
https://github.com/eutialia/open-in-iina-workflow
```

其中脚本只有两行
```
cd /Applications
open "iina://weblink?url={query}"
```

但是不知道iina-plus解析url+输入url的实现方式所以特来求助。

**Comment by xjbeta** [comment]
[URL Scheme](https://developer.apple.com/documentation/uikit/inter-process_communication/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app)
