### ISSUE TITLE
无法运行App

### ISSUE THREAD

**Issue by shen9712** [xjbeta/iina-plus#58]
如图
<img width="532" alt="image" src="https://user-images.githubusercontent.com/46221287/77226056-2bb63900-6bb0-11ea-80fc-99f4a84c4012.png">
<img width="532" alt="image" src="https://user-images.githubusercontent.com/46221287/77226061-353fa100-6bb0-11ea-8337-f87463f7e226.png">

**Comment by loveproe** [comment]
同样问题。。。。估计证书出问题了吧。

**Comment by LarenDorr** [comment]
+1
![Xnip2020-03-22_17-48-38](https://user-images.githubusercontent.com/23418465/77246779-72199f80-6c65-11ea-8293-bb1b70317d1e.jpg)

**Comment by PiaoL** [comment]
<img width="542" alt="issue-iina+" src="https://user-images.githubusercontent.com/15139973/77248236-d2fba480-6c72-11ea-8a55-13c844abc082.png">
Same issue.

**Comment by xyq038754** [comment]
Same issue.

**Comment by PiaoL** [comment]
Fork 下来 build 了一个版本临时用着，有需要请[自取](https://github.com/PiaoL/iina-plus/releases/tag/0.4.12(20032222))
但是有bug：弹幕功能失效了。

**Comment by xyq038754** [comment]
> Fork 下来 build 了一个版本临时用着，有需要请[自取](https://github.com/PiaoL/iina-plus/releases/tag/0.4.12(20032222))
> 但是有bug：弹幕功能失效了。

感谢！！！

**Comment by PiaoL** [comment]
[上一个版本](https://github.com/xjbeta/iina-plus/releases/tag/0.4.11(19120520))可以正常使用，弹幕功能也正常。

**Comment by xjbeta** [comment]
已修复  请重新下载 IINA  和IINA+
