### ISSUE TITLE
could you tell me how to install, i am a rookie

### ISSUE THREAD

**Issue by yangbao93** [xjbeta/iina-plus#6]
![image](https://user-images.githubusercontent.com/8946052/44951830-8179a200-aea1-11e8-8e45-939a56a09d26.png)
open .xcode*** file,where is it

**Comment by yangbao93** [comment]
thanks, it's my fault, i ignore dmg download url. i use source code. emmm,  i have a question ,when i install by dmg, my interface is different with yours, there is mine. 
![image](https://user-images.githubusercontent.com/8946052/44951899-b555c700-aea3-11e8-9497-f70604e06902.png)
no bilibili

**Comment by xjbeta** [comment]
Log in your account in "Preferences".

**Comment by CaptainYukinoshitaHachiman** [comment]
Well, to tell you the truth, you need to practice your grammar, especially the usage of conjunctions and tensesヽ(￣д￣;)ノ=3=3=3

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yangbao93** [comment]
Thank you. My English is really not good.
