### ISSUE TITLE
B 站直播弹幕不显示

### ISSUE THREAD

**Issue by Dreamacro** [xjbeta/iina-plus#74]
之前一段时间是好的，最近一段时间弹幕不出现了，而且打开一个直播后，再打开一个 B 站普通视频，直播窗口会出现后面打开视频的弹幕

**Comment by Dreamacro** [comment]
看起来问题已经修复，不如发个 release？

**Comment by xjbeta** [comment]
准备和一个大更新一起更新  再等两天
