### ISSUE TITLE
更新了最新的iina danmaku 12之后没有弹幕 是更新的原因么

### ISSUE THREAD

**Issue by ggfggggjqd** [xjbeta/iina-plus#79]

**Comment by xjbeta** [comment]
iina danmaku build12  需要  0.5.0 的iina-plus
旧版不再支持

**Comment by ggfggggjqd** [comment]
> iina danmaku build12 需要 0.5.0 的iina-plus
> 旧版不再支持

我也应更新了iina+ 到0.5.0 所以好像不是这个问题诶 但就是弹幕不再出现了

**Comment by xjbeta** [comment]
具体哪个没弹幕  还是所有的都没有
检查下
iina+ 的设置里  弹幕开了没
IINA.app 有没有放进 `/Applications/IINA.app`

**Comment by ggfggggjqd** [comment]
> 具体哪个没弹幕 还是所有的都没有
> 检查下
> iina+ 的设置里 弹幕开了没
> IINA.app 有没有放进 `/Applications/IINA.app`

试过斗鱼和虎牙都没弹幕。设置里确定开了 也放进了相应位置。

**Comment by xjbeta** [comment]
完全退出 IINA 和IINA+
打开 IINA+ 打开一个虎牙直播  等几秒  然后关掉IINA
同样操作打开一个斗鱼直播
然后回到IINA+   顶部菜单栏的help 里  有个log file  把内容发来看看

**Comment by ggfggggjqd** [comment]
HttpServer.swift[155], prepareWebSiteFiles(): Error Domain=NSCocoaErrorDomain Code=4 "“danmaku” couldn’t be removed." UserInfo={NSUserStringVariant=(
    Remove
), NSFilePath=/Users/dominator/Library/Application Support/com.xjbeta.iina-plus/danmaku, NSUnderlyingError=0x6000005ddc80 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
HttpServer.swift[126], start(): Server has started ( port = 19080 ). Try to connect now...
AppDelegate.swift[35], applicationDidFinishLaunching(_:): App did finish launch
AppDelegate.swift[38], applicationDidFinishLaunching(_:): App Version 0.5.0 (Build 20072018)
AppDelegate.swift[39], applicationDidFinishLaunching(_:): macOS Version 10.15.5 (Build 19F101)
AppDelegate.swift[42], applicationDidFinishLaunching(_:): 0.2 MB
MainViewController.swift[432], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
MainViewController.swift[432], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
Processes.swift[220], openWithPlayer(_:audioUrl:title:options:uuid:): Player arguments: ["http://al.flv.huya.com/src/7017534-7017534-30140079028568064-14158524-10057-A-0-1-imgplus.flv?wsSecret=f7f17ff3ec4578842f82de8da409772a&wsTime=5f16a783&fm=RFdxOEJjSjNoNkRKdDZUWV8kMF8kMV8kMl8kMw%3D%3D&ctyp=huya_tars&fs=bgct&&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*", "--mpv-force-media-title=rpg竞速，整", "--mpv-ytdl=no", "--danmaku", "--uuid=E27FF8D9-A854-4AF5-A3FE-B44E067D2B60"]
MainViewController.swift[432], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
Processes.swift[220], openWithPlayer(_:audioUrl:title:options:uuid:): Player arguments: ["https://tc-tct.douyucdn2.cn/dyliveflv1a/9999rcsj91rq1ep6.flv?wsAuth=bad30883d120bb708dbac95d5f2ece3e&token=web-h5-0-9999-26339a83b5a3e1149b936acb99b62d7493a0bb6862e07608&logo=0&expire=0&did=4a9e64a6a337853bcba9c40700031501&ver=Douyu_219111405&pt=2&st=0&origin=all&mix=0&isp=", "--mpv-force-media-title=吃鸡娱乐！ 9999", "--mpv-ytdl=no", "--danmaku", "--uuid=4462547B-8FDC-43C2-8869-F765409278F0"]
MainViewController.swift[432], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid

**Comment by xjbeta** [comment]
试试看在`/Users/dominator/Library/Application Support/com.xjbeta.iina-plus/`这个文件夹里
新建一个`danmaku`  的文件夹   然后重新打开IINA+

**Comment by ggfggggjqd** [comment]
可以了！万分感谢！

**Comment by xjbeta** [comment]
更新出新bug 了  马上修复....

**Comment by HighFLY622** [comment]
> 更新出新bug 了 马上修复....
您好 我是2020macbook m1 现在是0.5.16iina+和0.5.16iina，为什么看直播时没有弹幕呢，还有就是用iina打开url看视频打不开，我也是装了homebrew的，并且我的brew路径也是根据m1设置的/opt/homebrew/bin，但还是不行，您能帮我解决这两个问题吗

**Comment by HighFLY622** [comment]
> 请看在`/Users/dominator/Library/Application Support/com.xjbeta.iina-plus/`这个文件夹里
> 新建一个`danmaku` 的文件夹然后重新打开IINA +

更新出新bug 了 马上修复....
您好 我是2020macbook m1 现在是0.5.16iina+和0.5.16iina，为什么看直播时没有弹幕呢，还有就是用iina打开url看视频打不开，我也是装了homebrew的，并且我的brew路径也是根据m1设置的/opt/homebrew/bin，但还是不行，您能帮我解决这两个问题吗

**Comment by xjbeta** [comment]
> > 请看在`/Users/dominator/Library/Application Support/com.xjbeta.iina-plus/`这个文件夹里
> > 新建一个`danmaku` 的文件夹然后重新打开IINA +
> 
> 更新出新bug 了 马上修复....
> 您好 我是2020macbook m1 现在是0.5.16iina+和0.5.16iina，为什么看直播时没有弹幕呢，还有就是用iina打开url看视频打不开，我也是装了homebrew的，并且我的brew路径也是根据m1设置的/opt/homebrew/bin，但还是不行，您能帮我解决这两个问题吗

B站视频有弹幕吗  还是只有直播没弹幕  哪个直播网站没弹幕
IINA 打开URL 直接看视频  需要直链  某些链接需要额外的网络参数
IINA 直接打开网页视频(比如B站 youtube)   需要内置的youtube-dl 支持才行

**Comment by HighFLY622** [comment]
他已经存在一个dabmaku文件夹了。。。没法新建了 咋办 是斗鱼虎牙这些都没有弹幕 我是m1的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xjbeta ***@***.***&gt;
发送时间: 2021年5月18日 18:35
收件人: xjbeta/iina-plus ***@***.***&gt;
抄送: HighFLY622 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[xjbeta/iina-plus] 更新了最新的iina danmaku 12之后没有弹幕 是更新的原因么 (#79)





   
请看在/Users/dominator/Library/Application Support/com.xjbeta.iina-plus/这个文件夹里
 新建一个danmaku 的文件夹然后重新打开IINA +
  
更新出新bug 了 马上修复....
 您好 我是2020macbook m1 现在是0.5.16iina+和0.5.16iina，为什么看直播时没有弹幕呢，还有就是用iina打开url看视频打不开，我也是装了homebrew的，并且我的brew路径也是根据m1设置的/opt/homebrew/bin，但还是不行，您能帮我解决这两个问题吗
  
B站视频有弹幕吗  还是只有直播没弹幕  哪个直播网站没弹幕
 IINA 打开URL 直接看视频  需要直链  某些链接需要额外的网络参数
 IINA 直接打开网页视频(比如B站 youtube)   需要内置的youtube-dl 支持才行

**Comment by xjbeta** [comment]
> 他已经存在一个dabmaku文件夹了。。。没法新建了 咋办 是斗鱼虎牙这些都没有弹幕 我是m1的 发自我的iPhone
> […](#)

这个bug 已经修复了  你的和这个没什么关系  除非你用了某个旧版IINA+

**Comment by HighFLY622** [comment]
我用的就是0.5.16的版本，真的搞了好久了 就是没有弹幕。。。另外其实你们那个iina在介绍自定义youtube-dl的时候真应该向用户介绍一样 因为m1的安装路径是opt/homebrew/bin 这一点跟不是m1的mac完全不一样。。只是个建议



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xjbeta ***@***.***&gt;
发送时间: 2021年5月24日 17:59
收件人: xjbeta/iina-plus ***@***.***&gt;
抄送: HighFLY622 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[xjbeta/iina-plus] 更新了最新的iina danmaku 12之后没有弹幕 是更新的原因么 (#79)





  
他已经存在一个dabmaku文件夹了。。。没法新建了 咋办 是斗鱼虎牙这些都没有弹幕 我是m1的 发自我的iPhone
 …
  
这个bug 已经修复了  你的和这个没什么关系  除非你用了某个旧版IINA+
