### ISSUE TITLE
Not showing danmuku in some situations

### ISSUE THREAD

**Issue by CaptainYukinoshitaHachiman** [xjbeta/iina-plus#8]
The danmuku doesn't show when it's in full-screen mode or not on the top.

Maybe we can try to make a PY trade with IINA to make them open API to allow third-party apps add danmuku.

**Comment by CaptainYukinoshitaHachiman** [comment]
By the way this also happens when playing in PIP

**Comment by xjbeta** [comment]
https://github.com/xjbeta/iina-danmaku
