### ISSUE TITLE
是否可以让iina和iina-danmaku并存

### ISSUE THREAD

**Issue by sun11** [xjbeta/iina-plus#82]
已经安装了iina player，安装iina-danmaku的时候选择了保留二者，但可能是由于包里面命名的原因，launchpad里只显示原版的iina，finder里可以看到另一个iina，并且iina-plus也只能找到原版的iina，有没有办法使二者同时在launchpad显示和使用呢？

**Comment by xjbeta** [comment]
弹幕版和原版无法同时保留  并且需要放进 `/Applications/`  
建议只使用弹幕版的  除了无法用Sparkle 进行更新  签名不一样  不打开弹幕的情况下和原版没区别

**Comment by tofuliang** [comment]
> 已经安装了iina player，安装iina-danmaku的时候选择了保留二者，但可能是由于包里面命名的原因，launchpad里只显示原版的iina，finder里可以看到另一个iina，并且iina-plus也只能找到原版的iina，有没有办法使二者同时在launchpad显示和使用呢？

我也有同样的需求，原因有
1.无论时间长短iina-danmaku始终会比原版晚一点发布最新版本。打开就会提示有新版本可用，但实际上iina-danmaku并未跟进到最新版本。
2.看完B站视频一般不会彻底退出iina，如果此时使用看过B站视频的iina进程打开本地文件，会带有B站视频的那些弹幕，画面十分尴尬。
以前只要把iina-danmaku改名为IINA.app,原版IINA改名为IINA-Origin.app(不冲突即可)，两个版本的iina就可以共存，前段实际iina+更新后就不行了，除非先手动运行iina-danmaku，不然iina+就会调用原版IINA，且无法正常播放。
下午花时间看了下源码，最简单做法就是修改iina-danmaku里的`Info.plist`，把`CFBundleVersion`值改为小于15。
也试了下魔改途径，把iina-danmaku 和 iina+ 通信的scheme改掉，不和原版IINA的共用一个。
成果如下：

使用独立scheme的[iina-danmaku](https://github.com/tofuliang/iina-danmaku/actions/runs/738401775)
使用独立scheme的[iina+](https://github.com/tofuliang/iina-plus/actions/runs/738102953)

使用独立scheme后，不受文件名约束，可使用任意文件名，即可达到共存目的。

**Comment by xjbeta** [comment]
1. 弹幕版实际上没有内置的更新途径  暂时只能设置里关闭检查更新
  更新快慢基本取决于我什么时候看到IINA 本体更新了
  可能会考虑提供下内置的更新  但是最近IINA 基本暂停开发了  所以也不是太想更新新版
2. 这是个旧版本的bug  更新到最新版后应该能解决  无法解决再开个新issues
