### ISSUE TITLE
B站视频列表，会回到上面

### ISSUE THREAD

**Issue by forgmissyou** [xjbeta/iina-plus#83]
如题，登录B站账号，视频列表往后翻，点击一个视频观看后，回到列表，列表的位置会回到上面，不在原来点击视频的位置。不知道是不是设置的刷新？

**Comment by xjbeta** [comment]
新版已解决  刷新只会尝试加载新内容  不会全部刷新  导致已加载的内容被删除
可能会有些其他毛病?
