### ISSUE TITLE
请问番剧该怎么播放呢?

### ISSUE THREAD

**Issue by GuangdaJi** [xjbeta/iina-plus#85]

**Comment by hidohuang** [comment]
+1电影地址也无法解析

**Comment by xjbeta** [comment]
这两天我会尝试写一下

**Comment by xjbeta** [comment]
0.5.8  已支持 https://www.bilibili.com/bangumi/play/ep***** 格式的番剧视频
能够播放大会员视频
付费视频/电影暂时没有测试
