### ISSUE TITLE
能否不用进入二级链接打开直播？

### ISSUE THREAD

**Issue by masonme** [xjbeta/iina-plus#86]
1. 双击点击一位主播直播，打开的是他直播标题，还需要再次双击标题才能打开IINA看直播，请问能否省略此步骤？
2. 如果1解决了，再观看其他直播就不用再返回，很方便。

**Comment by xjbeta** [comment]
原因是没办法打开IINA 后在IINA 内切换线路/清晰度
暂时只能这样  看之后IINA 的插件能否解决
