### ISSUE TITLE
请问可不可以做成safari/chrome/alfred插件的形式呢? 感觉安装另一个版本的软件在homebrew里管理不太方便

### ISSUE THREAD

**Issue by GuangdaJi** [xjbeta/iina-plus#87]
RT, 如果可以不胜感激!!!

**Comment by xjbeta** [comment]
无法实现

不是简单的转换就能变成一个浏览器插件的
IINA+ 完全由Swift 写的  浏览器插件用的是js html 之类的前端相关的  (Safari 可能能用一部分Swift)
