### ISSUE TITLE
更新了IINA-1.1.1-Danmaku(15)之后，每一个直播间都没有弹幕显示。

### ISSUE THREAD

**Issue by ggfggggjqd** [xjbeta/iina-plus#89]
![image](https://user-images.githubusercontent.com/63317695/100536758-a36b5600-325d-11eb-920d-cfcaddf3743e.png)

**Comment by ggfggggjqd** [comment]
h5-0-52319-8b720a50dbc2c35f53879a8cd63492e80c0746f6fdc629ad&logo=0&expire=0&did=c8b791719747d4014e026a1d00061601&ver=Douyu_219111405&pt=2&st=0&origin=ws&mix=0&isp=", "--mpv-force-media-title=29号下午全民杯19点决赛 打太常规", "--mpv-ytdl=no", "--danmaku", "--uuid=C6325B80-877B-4554-B1B3-C1F8F1C3118D"]
MainViewController.swift[431], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
MainViewController.swift[431], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
Processes.swift[220], openWithPlayer(_:audioUrl:title:options:uuid:): Player arguments: ["https://pcdn-a1a.douyucdn.cn/live/9999rSfC2pXfPpCv.flv?wsAuth=92b78f4deb3b348a019e08dc18d8015f&token=web-h5-0-9999-26339a83b5a3e11434f91aceb39de3badd0500c71cbbaacd&logo=0&expire=0&did=3e9622d9d285819a8187bf9c00061601&ver=Douyu_219111405&pt=2&st=0&origin=tct&mix=0&isp=&pushdouyu=1", "--mpv-force-media-title=看比赛，学技术！", "--mpv-ytdl=no", "--danmaku", "--uuid=53557317-CBEA-4D2E-B0EF-EEFBA791D0D2"]
MainViewController.swift[431], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
MainViewController.swift[431], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid

**Comment by xjbeta** [comment]
斗鱼的弹幕好像失效了
其他平台的直播呢?

**Comment by ggfggggjqd** [comment]
> 斗鱼的弹幕好像失效了
> 其他平台的直播呢?
虎牙也不行
wsSecret=c9a6f80bfd2257b1c81270a9339090e3&wsTime=5fc39210&fm=RFdxOEJjSjNoNkRKdDZUWV8kMF8kMV8kMl8kMw%3D%3D&ctyp=huya_tars&fs=bgct&&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&ratio=0", "--mpv-force-media-title=决赛TSG-ZERO 夺冠抽崭新野荷", "--mpv-ytdl=no", "--danmaku", "--uuid=69FC7FE9-B3BD-46EB-83E4-FC59D55B679F"]
MainViewController.swift[431], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid
MainViewController.swift[431], loadBilibiliCards(_:): Get bilibili dynamicList error: Key not found: data.mid

**Comment by xjbeta** [comment]
确实  虎牙也挂了....

**Comment by xjbeta** [comment]
我推了个新版本[0.5.4](https://github.com/xjbeta/iina-plus/releases/tag/0.5.4(20112920))  配上[1.1.2 的IINA-Danmaku](https://github.com/xjbeta/iina-danmaku/releases/tag/v1.1.2-Danmaku(15))  应该就没问题了
0.5.4 可能没办法用官方的IINA   下个版本再修复了(
