### ISSUE TITLE
可以选不同清晰度的直播吗

### ISSUE THREAD

**Issue by duzhen1996** [xjbeta/iina-plus#90]
现在只能选最高清晰度

**Comment by duzhen1996** [comment]
https://github.com/wbt5/real-url，希望这个可以帮到你，我看B站和斗鱼的直播清晰度至少都是可选的，请求的json改个参数就行。我现在用这个暂时替代iina+

**Comment by xjbeta** [comment]
有在计划内  但是短期内不准备做
