### ISSUE TITLE
请附加一个 mpv播放器。

### ISSUE THREAD

**Issue by MrEri** [xjbeta/iina-plus#91]
请附加一个 mpv播放器。
**/Applications/mpv.app**

**Comment by xjbeta** [comment]
mpv 暂时只能用命令行  
可以给mpv.app里的mpv 创建个软链 终端内执行
`ln -s /Applications/mpv.app/Contents/MacOS/mpv /usr/local/bin/mpv`

**Comment by MrEri** [comment]
/Applications/mpv.app. 用法：
open -a mpv **url** --args --force-media-title=纯音乐 --ytdl=no --referrer=https://www.bilibili.com/ --really-quiet
