### ISSUE TITLE
虎牙有些直播无法播放

### ISSUE THREAD

**Issue by 0x1301FDF** [xjbeta/iina-plus#97]
例如 url：https://www.huya.com/333003，iina打开解析之后的url之后闪退

log：
MainViewController.swift[388], startSearchingUrl(_:directly:): decodeUrl success: https://www.huya.com/333003
Processes.swift[343], openWithIINAUrlScheme(_:args:uuid:): Open IINA URL:  iina://open?url=https%3A%2F%2Fal.flv.huya.com%2Fsrc%2F2367547387-2367547387-10168538598895255552-4735218230-10057-A-0-1.flv%3FwsSecret%3D16c0a78e09d4afb73c0710f753b91777%26wsTime%3D6033cbec%26fm%3DRFdxOEJjSjNoNkRKdDZUWV8kMF8kMV8kMl8kMw%253D%253D%26ctyp%3Dhuya_tars%26txyp%3Do%253Asjz2%253B%26fs%3Dbgct%26%26sphdcdn%3Dal_7-tx_3-js_3-ws_7-bd_2-hw_2%26sphdDC%3Dhuya%26sphd%3D264_%2A-265_%2A%26ratio%3D0&mpv_force-media-title=%E8%8A%9C%E6%B9%96%20%E6%97%A0%E9%99%90%E7%81%AB%E5%8A%9B%E8%B5%B7%E9%A3%9E&mpv_ytdl=no

**Comment by xjbeta** [comment]
https://github.com/xjbeta/iina-plus/releases/tag/0.5.11(21022211)
先更新一下IINA+   晚上等开播了我会测试一下

**Comment by xjbeta** [comment]
没有复现

**Comment by 0x1301FDF** [comment]
有点奇葩，这主播过完年回来之后，直播就正常了
