### ISSUE TITLE
更新后解析bili 直播错误。

### ISSUE THREAD

**Issue by MrEri** [xjbeta/iina-plus#98]
如题。日志如下：
LiveStatusTableCellView.swift[48], getInfo(): Get live status error: Key not found: data.room_id

**Comment by xjbeta** [comment]
直播间链接发下?
无法重现

**Comment by MrEri** [comment]
https://live.bilibili.com/397064

**Comment by xjbeta** [comment]
`https://api.live.bilibili.com/room/v1/Room/get_info?room_id=397064`
浏览器内打开这个链接 (B站直播间信息的API接口   别开任何代理)
正常是下面这样的内容

`{"code":0,"msg":"ok","message":"ok","data":{"uid":246417,"room_id":397064,"short_id":0,"attention":3046,"online":421,"is_portrait":false,"description":"<p>7*24小时休闲作业挂机直播间</p>\n<h3><strong>主播看不到弹幕,有事的话可以发私信，感谢各位辣条礼物</strong></h3>\n<h3><strong>图在动态里，评论里有网盘地址，</strong><strong><a href=\"https://share.weiyun.com/5JRU144\" target=\"_blank\">网页可以直接点击网盘地址</a></strong></h3>","live_status":1,"area_id":33,"parent_area_id":10,"parent_area_name":"生活","old_area_id":7,"background":"https://i0.hdslb.com/bfs/live/room_bg/e7d3d92496eb93c2a63cd635a90dc3abb4591d98.jpg","title":"纯音乐","user_cover":"https://i0.hdslb.com/bfs/live/cf8636cb812ccf942000c82b7b221c6e0986be8d.jpg","keyframe":"https://i0.hdslb.com/bfs/live/keyframe02231536000000397064ofht6m.jpg","is_strict_room":false,"live_time":"2021-02-01 18:43:32","tags":"纯音乐,作业用,放松,BGM,学习","is_anchor":0,"room_silent_type":"","room_silent_level":0,"room_silent_second":0,"area_name":"影音馆","pendants":"","area_pendants":"","hot_words":["2333333","喂，妖妖零吗","红红火火恍恍惚惚","FFFFFFFFFF","Yooooooo","啪啪啪啪啪","666666666","老司机带带我","你为什么这么熟练啊","gg","prprpr","向大佬低头","请大家注意弹幕礼仪哦！","还有这种操作！","囍","打call","你气不气？","队友呢？"],"hot_words_status":0,"verify":"","new_pendants":{"frame":{"name":"","value":"","position":0,"desc":"","area":0,"area_old":0,"bg_color":"","bg_pic":"","use_old_area":false},"badge":null,"mobile_frame":{"name":"","value":"","position":0,"desc":"","area":0,"area_old":0,"bg_color":"","bg_pic":"","use_old_area":false},"mobile_badge":null},"up_session":"118605955671133960","pk_status":0,"pk_id":0,"battle_id":0,"allow_change_area_time":0,"allow_upload_cover_time":0,"studio_info":{"status":0,"master_list":[]}}}`

**Comment by MrEri** [comment]
{"code":-412,"message":"请求被拦截","ttl":1,"data":null}
浏览器打开直播间是正常的。

**Comment by xjbeta** [comment]
412 短时间内请求次数过多  被暂时ban了(
