### ISSUE TITLE
B站番剧无法解析

### ISSUE THREAD

**Issue by liudorangefly** [xjbeta/iina-plus#99]
最近更新后b站的番剧无法解析了之前可以，在更换了旧版本软件后发现仍然无法解析，推测b站改了接口
贴一个测试链接： https://www.bilibili.com/bangumi/play/ep340149

<img width="527" alt="截屏2021-02-26 下午8 30 50" src="https://user-images.githubusercontent.com/17426718/109300502-8c92ca80-7871-11eb-92e1-95178288a64e.png">

**Comment by xjbeta** [comment]
改错了行代码  马上推更新修复(
